require "json"
require "time"

module Aws
  module EKSAuth
    module Types

      # You don't have permissions to perform the requested operation. The IAM principal making the request
      # must have at least one IAM permissions policy attached that grants the required permissions. For
      # more information, see Access management in the IAM User Guide .

      struct AccessDeniedException
        include JSON::Serializable


        @[JSON::Field(key: "message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end


      struct AssumeRoleForPodIdentityRequest
        include JSON::Serializable

        # The name of the cluster for the request.

        @[JSON::Field(key: "clusterName")]
        getter cluster_name : String

        # The token of the Kubernetes service account for the pod.

        @[JSON::Field(key: "token")]
        getter token : String

        def initialize(
          @cluster_name : String,
          @token : String
        )
        end
      end


      struct AssumeRoleForPodIdentityResponse
        include JSON::Serializable

        # An object with the permanent IAM role identity and the temporary session name. The ARN of the IAM
        # role that the temporary credentials authenticate to. The session name of the temporary session
        # requested to STS. The value is a unique identifier that contains the role ID, a colon ( : ), and the
        # role session name of the role that is being assumed. The role ID is generated by IAM when the role
        # is created. The role session name part of the value follows this format: eks- clustername - podname
        # - random UUID

        @[JSON::Field(key: "assumedRoleUser")]
        getter assumed_role_user : Types::AssumedRoleUser

        # The identity that is allowed to use the credentials. This value is always pods.eks.amazonaws.com .

        @[JSON::Field(key: "audience")]
        getter audience : String

        # The Amazon Web Services Signature Version 4 type of temporary credentials.

        @[JSON::Field(key: "credentials")]
        getter credentials : Types::Credentials

        # The Amazon Resource Name (ARN) and ID of the EKS Pod Identity association.

        @[JSON::Field(key: "podIdentityAssociation")]
        getter pod_identity_association : Types::PodIdentityAssociation

        # The name of the Kubernetes service account inside the cluster to associate the IAM credentials with.

        @[JSON::Field(key: "subject")]
        getter subject : Types::Subject

        def initialize(
          @assumed_role_user : Types::AssumedRoleUser,
          @audience : String,
          @credentials : Types::Credentials,
          @pod_identity_association : Types::PodIdentityAssociation,
          @subject : Types::Subject
        )
        end
      end

      # An object with the permanent IAM role identity and the temporary session name.

      struct AssumedRoleUser
        include JSON::Serializable

        # The ARN of the IAM role that the temporary credentials authenticate to.

        @[JSON::Field(key: "arn")]
        getter arn : String

        # The session name of the temporary session requested to STS. The value is a unique identifier that
        # contains the role ID, a colon ( : ), and the role session name of the role that is being assumed.
        # The role ID is generated by IAM when the role is created. The role session name part of the value
        # follows this format: eks- clustername - podname - random UUID

        @[JSON::Field(key: "assumeRoleId")]
        getter assume_role_id : String

        def initialize(
          @arn : String,
          @assume_role_id : String
        )
        end
      end

      # The Amazon Web Services Signature Version 4 type of temporary credentials.

      struct Credentials
        include JSON::Serializable

        # The access key ID that identifies the temporary security credentials.

        @[JSON::Field(key: "accessKeyId")]
        getter access_key_id : String

        # The Unix epoch timestamp in seconds when the current credentials expire.

        @[JSON::Field(key: "expiration")]
        getter expiration : Time

        # The secret access key that applications inside the pods use to sign requests.

        @[JSON::Field(key: "secretAccessKey")]
        getter secret_access_key : String

        # The token that applications inside the pods must pass to any service API to use the temporary
        # credentials.

        @[JSON::Field(key: "sessionToken")]
        getter session_token : String

        def initialize(
          @access_key_id : String,
          @expiration : Time,
          @secret_access_key : String,
          @session_token : String
        )
        end
      end

      # The specified Kubernetes service account token is expired.

      struct ExpiredTokenException
        include JSON::Serializable


        @[JSON::Field(key: "message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # These errors are usually caused by a server-side issue.

      struct InternalServerException
        include JSON::Serializable


        @[JSON::Field(key: "message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # The specified parameter is invalid. Review the available parameters for the API request.

      struct InvalidParameterException
        include JSON::Serializable


        @[JSON::Field(key: "message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # This exception is thrown if the request contains a semantic error. The precise meaning will depend
      # on the API, and will be documented in the error message.

      struct InvalidRequestException
        include JSON::Serializable


        @[JSON::Field(key: "message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # The specified Kubernetes service account token is invalid.

      struct InvalidTokenException
        include JSON::Serializable


        @[JSON::Field(key: "message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # Amazon EKS Pod Identity associations provide the ability to manage credentials for your
      # applications, similar to the way that Amazon EC2 instance profiles provide credentials to Amazon EC2
      # instances.

      struct PodIdentityAssociation
        include JSON::Serializable

        # The Amazon Resource Name (ARN) of the EKS Pod Identity association.

        @[JSON::Field(key: "associationArn")]
        getter association_arn : String

        # The ID of the association.

        @[JSON::Field(key: "associationId")]
        getter association_id : String

        def initialize(
          @association_arn : String,
          @association_id : String
        )
        end
      end

      # The specified resource could not be found.

      struct ResourceNotFoundException
        include JSON::Serializable


        @[JSON::Field(key: "message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # The service is unavailable. Back off and retry the operation.

      struct ServiceUnavailableException
        include JSON::Serializable


        @[JSON::Field(key: "message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # An object containing the name of the Kubernetes service account inside the cluster to associate the
      # IAM credentials with.

      struct Subject
        include JSON::Serializable

        # The name of the Kubernetes namespace inside the cluster to create the association in. The service
        # account and the pods that use the service account must be in this namespace.

        @[JSON::Field(key: "namespace")]
        getter namespace : String

        # The name of the Kubernetes service account inside the cluster to associate the IAM credentials with.

        @[JSON::Field(key: "serviceAccount")]
        getter service_account : String

        def initialize(
          @namespace : String,
          @service_account : String
        )
        end
      end

      # The request was denied because your request rate is too high. Reduce the frequency of requests.

      struct ThrottlingException
        include JSON::Serializable


        @[JSON::Field(key: "message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end
    end
  end
end
