# Generated by build_tools/crystal_sdk_generator/partitions_generator.cr. Do not edit.
module Aws
  module Runtime
    module PartitionsData
      record Partition,
        regions : Array(String),
        region_regex : Regex,
        dns_suffix : String,
        dualstack_dns_suffix : String,
        supports_dualstack : Bool,
        supports_fips : Bool

      DEFAULT_DNS_SUFFIX = "amazonaws.com"

      ALL = [
        Partition.new(
          regions: ["af-south-1", "ap-east-1", "ap-east-2", "ap-northeast-1", "ap-northeast-2", "ap-northeast-3", "ap-south-1", "ap-south-2", "ap-southeast-1", "ap-southeast-2", "ap-southeast-3", "ap-southeast-4", "ap-southeast-5", "ap-southeast-6", "ap-southeast-7", "ca-central-1", "ca-west-1", "eu-central-1", "eu-central-2", "eu-north-1", "eu-south-1", "eu-south-2", "eu-west-1", "eu-west-2", "eu-west-3", "il-central-1", "me-central-1", "me-south-1", "mx-central-1", "sa-east-1", "us-east-1", "us-east-2", "us-west-1", "us-west-2"],
          region_regex: Regex.new("^(us|eu|ap|sa|ca|me|af|il|mx)\\-\\w+\\-\\d+$"),
          dns_suffix: "amazonaws.com",
          dualstack_dns_suffix: "api.aws",
          supports_dualstack: true,
          supports_fips: true,
        ),
        Partition.new(
          regions: ["cn-north-1", "cn-northwest-1"],
          region_regex: Regex.new("^cn\\-\\w+\\-\\d+$"),
          dns_suffix: "amazonaws.com.cn",
          dualstack_dns_suffix: "api.amazonwebservices.com.cn",
          supports_dualstack: true,
          supports_fips: true,
        ),
        Partition.new(
          regions: ["us-gov-east-1", "us-gov-west-1"],
          region_regex: Regex.new("^us\\-gov\\-\\w+\\-\\d+$"),
          dns_suffix: "amazonaws.com",
          dualstack_dns_suffix: "api.aws",
          supports_dualstack: true,
          supports_fips: true,
        ),
        Partition.new(
          regions: ["us-iso-east-1", "us-iso-west-1"],
          region_regex: Regex.new("^us\\-iso\\-\\w+\\-\\d+$"),
          dns_suffix: "c2s.ic.gov",
          dualstack_dns_suffix: "c2s.ic.gov",
          supports_dualstack: false,
          supports_fips: true,
        ),
        Partition.new(
          regions: ["us-isob-east-1", "us-isob-west-1"],
          region_regex: Regex.new("^us\\-isob\\-\\w+\\-\\d+$"),
          dns_suffix: "sc2s.sgov.gov",
          dualstack_dns_suffix: "sc2s.sgov.gov",
          supports_dualstack: false,
          supports_fips: true,
        ),
        Partition.new(
          regions: ["eu-isoe-west-1"],
          region_regex: Regex.new("^eu\\-isoe\\-\\w+\\-\\d+$"),
          dns_suffix: "cloud.adc-e.uk",
          dualstack_dns_suffix: "cloud.adc-e.uk",
          supports_dualstack: false,
          supports_fips: true,
        ),
        Partition.new(
          regions: ["us-isof-east-1", "us-isof-south-1"],
          region_regex: Regex.new("^us\\-isof\\-\\w+\\-\\d+$"),
          dns_suffix: "csp.hci.ic.gov",
          dualstack_dns_suffix: "csp.hci.ic.gov",
          supports_dualstack: false,
          supports_fips: true,
        ),
        Partition.new(
          regions: ["eusc-de-east-1"],
          region_regex: Regex.new("^eusc\\-(de)\\-\\w+\\-\\d+$"),
          dns_suffix: "amazonaws.eu",
          dualstack_dns_suffix: "api.amazonwebservices.eu",
          supports_dualstack: true,
          supports_fips: true,
        ),
      ] of Partition
    end
  end
end
