require "json"
require "time"

module AwsSdk
  module Budgets
    module Types

      # You are not authorized to use this operation with the given parameters.

      struct AccessDeniedException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # A budget action resource.

      struct Action
        include JSON::Serializable

        # A system-generated universally unique identifier (UUID) for the action.

        @[JSON::Field(key: "ActionId")]
        getter action_id : String

        # The trigger threshold of the action.

        @[JSON::Field(key: "ActionThreshold")]
        getter action_threshold : Types::ActionThreshold

        # The type of action. This defines the type of tasks that can be carried out by this action. This
        # field also determines the format for definition.

        @[JSON::Field(key: "ActionType")]
        getter action_type : String

        # This specifies if the action needs manual or automatic approval.

        @[JSON::Field(key: "ApprovalModel")]
        getter approval_model : String


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        # Where you specify all of the type-specific parameters.

        @[JSON::Field(key: "Definition")]
        getter definition : Types::Definition

        # The role passed for action execution and reversion. Roles and actions must be in the same account.

        @[JSON::Field(key: "ExecutionRoleArn")]
        getter execution_role_arn : String


        @[JSON::Field(key: "NotificationType")]
        getter notification_type : String

        # The status of the action.

        @[JSON::Field(key: "Status")]
        getter status : String


        @[JSON::Field(key: "Subscribers")]
        getter subscribers : Array(Types::Subscriber)

        def initialize(
          @action_id : String,
          @action_threshold : Types::ActionThreshold,
          @action_type : String,
          @approval_model : String,
          @budget_name : String,
          @definition : Types::Definition,
          @execution_role_arn : String,
          @notification_type : String,
          @status : String,
          @subscribers : Array(Types::Subscriber)
        )
        end
      end

      # The historical records for a budget action.

      struct ActionHistory
        include JSON::Serializable

        # The description of the details for the event.

        @[JSON::Field(key: "ActionHistoryDetails")]
        getter action_history_details : Types::ActionHistoryDetails

        # This distinguishes between whether the events are triggered by the user or are generated by the
        # system.

        @[JSON::Field(key: "EventType")]
        getter event_type : String

        # The status of action at the time of the event.

        @[JSON::Field(key: "Status")]
        getter status : String


        @[JSON::Field(key: "Timestamp", converter: AwsSdk::Runtime::UnixTimestampConverter)]
        getter timestamp : Time

        def initialize(
          @action_history_details : Types::ActionHistoryDetails,
          @event_type : String,
          @status : String,
          @timestamp : Time
        )
        end
      end

      # The description of the details for the event.

      struct ActionHistoryDetails
        include JSON::Serializable

        # The budget action resource.

        @[JSON::Field(key: "Action")]
        getter action : Types::Action


        @[JSON::Field(key: "Message")]
        getter message : String

        def initialize(
          @action : Types::Action,
          @message : String
        )
        end
      end

      # The trigger threshold of the action.

      struct ActionThreshold
        include JSON::Serializable


        @[JSON::Field(key: "ActionThresholdType")]
        getter action_threshold_type : String


        @[JSON::Field(key: "ActionThresholdValue")]
        getter action_threshold_value : Float64

        def initialize(
          @action_threshold_type : String,
          @action_threshold_value : Float64
        )
        end
      end

      # The parameters that determine the budget amount for an auto-adjusting budget.

      struct AutoAdjustData
        include JSON::Serializable

        # The string that defines whether your budget auto-adjusts based on historical or forecasted data.

        @[JSON::Field(key: "AutoAdjustType")]
        getter auto_adjust_type : String

        # The parameters that define or describe the historical data that your auto-adjusting budget is based
        # on.

        @[JSON::Field(key: "HistoricalOptions")]
        getter historical_options : Types::HistoricalOptions?

        # The last time that your budget was auto-adjusted.

        @[JSON::Field(key: "LastAutoAdjustTime", converter: AwsSdk::Runtime::UnixTimestampConverter)]
        getter last_auto_adjust_time : Time?

        def initialize(
          @auto_adjust_type : String,
          @historical_options : Types::HistoricalOptions? = nil,
          @last_auto_adjust_time : Time? = nil
        )
        end
      end

      # The billing view status must be HEALTHY to perform this action. Try again when the status is
      # HEALTHY.

      struct BillingViewHealthStatusException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # Represents the output of the CreateBudget operation. The content consists of the detailed metadata
      # and data file information, and the current status of the budget object. This is the Amazon Resource
      # Name (ARN) pattern for a budget: arn:aws:budgets::AccountId:budget/budgetName

      struct Budget
        include JSON::Serializable

        # The name of a budget. The name must be unique within an account. The : and \ characters, and the
        # "/action/" substring, aren't allowed in BudgetName .

        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        # Specifies whether this budget tracks costs, usage, RI utilization, RI coverage, Savings Plans
        # utilization, or Savings Plans coverage.

        @[JSON::Field(key: "BudgetType")]
        getter budget_type : String

        # The length of time until a budget resets the actual and forecasted spend.

        @[JSON::Field(key: "TimeUnit")]
        getter time_unit : String

        # The parameters that determine the budget amount for an auto-adjusting budget.

        @[JSON::Field(key: "AutoAdjustData")]
        getter auto_adjust_data : Types::AutoAdjustData?

        # The Amazon Resource Name (ARN) that uniquely identifies a specific billing view. The ARN is used to
        # specify which particular billing view you want to interact with or retrieve information from when
        # making API calls related to Amazon Web Services Billing and Cost Management features. The
        # BillingViewArn can be retrieved by calling the ListBillingViews API.

        @[JSON::Field(key: "BillingViewArn")]
        getter billing_view_arn : String?

        # The total amount of cost, usage, RI utilization, RI coverage, Savings Plans utilization, or Savings
        # Plans coverage that you want to track with your budget. BudgetLimit is required for cost or usage
        # budgets, but optional for RI or Savings Plans utilization or coverage budgets. RI and Savings Plans
        # utilization or coverage budgets default to 100 . This is the only valid value for RI or Savings
        # Plans utilization or coverage budgets. You can't use BudgetLimit with PlannedBudgetLimits for
        # CreateBudget and UpdateBudget actions.

        @[JSON::Field(key: "BudgetLimit")]
        getter budget_limit : Types::Spend?

        # The actual and forecasted cost or usage that the budget tracks.

        @[JSON::Field(key: "CalculatedSpend")]
        getter calculated_spend : Types::CalculatedSpend?

        # The cost filters, such as Region , Service , LinkedAccount , Tag , or CostCategory , that are
        # applied to a budget. Amazon Web Services Budgets supports the following services as a Service filter
        # for RI budgets: Amazon EC2 Amazon Redshift Amazon Relational Database Service Amazon ElastiCache
        # Amazon OpenSearch Service

        @[JSON::Field(key: "CostFilters")]
        getter cost_filters : Hash(String, Array(String))?

        # The types of costs that are included in this COST budget. USAGE , RI_UTILIZATION , RI_COVERAGE ,
        # SAVINGS_PLANS_UTILIZATION , and SAVINGS_PLANS_COVERAGE budgets do not have CostTypes .

        @[JSON::Field(key: "CostTypes")]
        getter cost_types : Types::CostTypes?

        # The filtering dimensions for the budget and their corresponding values.

        @[JSON::Field(key: "FilterExpression")]
        getter filter_expression : Types::Expression?

        # The current operational state of a Billing View derived resource.

        @[JSON::Field(key: "HealthStatus")]
        getter health_status : Types::HealthStatus?

        # The last time that you updated this budget.

        @[JSON::Field(key: "LastUpdatedTime", converter: AwsSdk::Runtime::UnixTimestampConverter)]
        getter last_updated_time : Time?

        # The definition for how the budget data is aggregated.

        @[JSON::Field(key: "Metrics")]
        getter metrics : Array(String)?

        # A map containing multiple BudgetLimit , including current or future limits. PlannedBudgetLimits is
        # available for cost or usage budget and supports both monthly and quarterly TimeUnit . For monthly
        # budgets, provide 12 months of PlannedBudgetLimits values. This must start from the current month and
        # include the next 11 months. The key is the start of the month, UTC in epoch seconds. For quarterly
        # budgets, provide four quarters of PlannedBudgetLimits value entries in standard calendar quarter
        # increments. This must start from the current quarter and include the next three quarters. The key is
        # the start of the quarter, UTC in epoch seconds. If the planned budget expires before 12 months for
        # monthly or four quarters for quarterly, provide the PlannedBudgetLimits values only for the
        # remaining periods. If the budget begins at a date in the future, provide PlannedBudgetLimits values
        # from the start date of the budget. After all of the BudgetLimit values in PlannedBudgetLimits are
        # used, the budget continues to use the last limit as the BudgetLimit . At that point, the planned
        # budget provides the same experience as a fixed budget. DescribeBudget and DescribeBudgets response
        # along with PlannedBudgetLimits also contain BudgetLimit representing the current month or quarter
        # limit present in PlannedBudgetLimits . This only applies to budgets that are created with
        # PlannedBudgetLimits . Budgets that are created without PlannedBudgetLimits only contain BudgetLimit
        # . They don't contain PlannedBudgetLimits .

        @[JSON::Field(key: "PlannedBudgetLimits")]
        getter planned_budget_limits : Hash(String, Types::Spend)?

        # The period of time that's covered by a budget. You set the start date and end date. The start date
        # must come before the end date. The end date must come before 06/15/87 00:00 UTC . If you create your
        # budget and don't specify a start date, Amazon Web Services defaults to the start of your chosen time
        # period (DAILY, MONTHLY, QUARTERLY, ANNUALLY, or CUSTOM). For example, if you created your budget on
        # January 24, 2018, chose DAILY , and didn't set a start date, Amazon Web Services set your start date
        # to 01/24/18 00:00 UTC . If you chose MONTHLY , Amazon Web Services set your start date to 01/01/18
        # 00:00 UTC . If you didn't specify an end date, Amazon Web Services set your end date to 06/15/87
        # 00:00 UTC . The defaults are the same for the Billing and Cost Management console and the API. You
        # can change either date with the UpdateBudget operation. After the end date, Amazon Web Services
        # deletes the budget and all the associated notifications and subscribers.

        @[JSON::Field(key: "TimePeriod")]
        getter time_period : Types::TimePeriod?

        def initialize(
          @budget_name : String,
          @budget_type : String,
          @time_unit : String,
          @auto_adjust_data : Types::AutoAdjustData? = nil,
          @billing_view_arn : String? = nil,
          @budget_limit : Types::Spend? = nil,
          @calculated_spend : Types::CalculatedSpend? = nil,
          @cost_filters : Hash(String, Array(String))? = nil,
          @cost_types : Types::CostTypes? = nil,
          @filter_expression : Types::Expression? = nil,
          @health_status : Types::HealthStatus? = nil,
          @last_updated_time : Time? = nil,
          @metrics : Array(String)? = nil,
          @planned_budget_limits : Hash(String, Types::Spend)? = nil,
          @time_period : Types::TimePeriod? = nil
        )
        end
      end

      # The budget name and associated notifications for an account.

      struct BudgetNotificationsForAccount
        include JSON::Serializable


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String?


        @[JSON::Field(key: "Notifications")]
        getter notifications : Array(Types::Notification)?

        def initialize(
          @budget_name : String? = nil,
          @notifications : Array(Types::Notification)? = nil
        )
        end
      end

      # A history of the state of a budget at the end of the budget's specified time period.

      struct BudgetPerformanceHistory
        include JSON::Serializable

        # The Amazon Resource Name (ARN) that uniquely identifies a specific billing view. The ARN is used to
        # specify which particular billing view you want to interact with or retrieve information from when
        # making API calls related to Amazon Web Services Billing and Cost Management features. The
        # BillingViewArn can be retrieved by calling the ListBillingViews API.

        @[JSON::Field(key: "BillingViewArn")]
        getter billing_view_arn : String?


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String?


        @[JSON::Field(key: "BudgetType")]
        getter budget_type : String?

        # A list of amounts of cost or usage that you created budgets for, which are compared to your actual
        # costs or usage.

        @[JSON::Field(key: "BudgetedAndActualAmountsList")]
        getter budgeted_and_actual_amounts_list : Array(Types::BudgetedAndActualAmounts)?

        # The history of the cost filters for a budget during the specified time period.

        @[JSON::Field(key: "CostFilters")]
        getter cost_filters : Hash(String, Array(String))?

        # The history of the cost types for a budget during the specified time period.

        @[JSON::Field(key: "CostTypes")]
        getter cost_types : Types::CostTypes?


        @[JSON::Field(key: "TimeUnit")]
        getter time_unit : String?

        def initialize(
          @billing_view_arn : String? = nil,
          @budget_name : String? = nil,
          @budget_type : String? = nil,
          @budgeted_and_actual_amounts_list : Array(Types::BudgetedAndActualAmounts)? = nil,
          @cost_filters : Hash(String, Array(String))? = nil,
          @cost_types : Types::CostTypes? = nil,
          @time_unit : String? = nil
        )
        end
      end

      # The amount of cost or usage that you created the budget for, compared to your actual costs or usage.

      struct BudgetedAndActualAmounts
        include JSON::Serializable

        # Your actual costs or usage for a budget period.

        @[JSON::Field(key: "ActualAmount")]
        getter actual_amount : Types::Spend?

        # The amount of cost or usage that you created the budget for.

        @[JSON::Field(key: "BudgetedAmount")]
        getter budgeted_amount : Types::Spend?

        # The time period that's covered by this budget comparison.

        @[JSON::Field(key: "TimePeriod")]
        getter time_period : Types::TimePeriod?

        def initialize(
          @actual_amount : Types::Spend? = nil,
          @budgeted_amount : Types::Spend? = nil,
          @time_period : Types::TimePeriod? = nil
        )
        end
      end

      # The spend objects that are associated with this budget. The actualSpend tracks how much you've used,
      # cost, usage, RI units, or Savings Plans units and the forecastedSpend tracks how much that you're
      # predicted to spend based on your historical usage profile. For example, if it's the 20th of the
      # month and you have spent 50 dollars on Amazon EC2, your actualSpend is 50 USD , and your
      # forecastedSpend is 75 USD .

      struct CalculatedSpend
        include JSON::Serializable

        # The amount of cost, usage, RI units, or Savings Plans units that you used.

        @[JSON::Field(key: "ActualSpend")]
        getter actual_spend : Types::Spend

        # The amount of cost, usage, RI units, or Savings Plans units that you're forecasted to use.

        @[JSON::Field(key: "ForecastedSpend")]
        getter forecasted_spend : Types::Spend?

        def initialize(
          @actual_spend : Types::Spend,
          @forecasted_spend : Types::Spend? = nil
        )
        end
      end

      # The cost category values used for filtering the costs.

      struct CostCategoryValues
        include JSON::Serializable

        # The unique name of the cost category.

        @[JSON::Field(key: "Key")]
        getter key : String?

        # The match options that you can use to filter your results.

        @[JSON::Field(key: "MatchOptions")]
        getter match_options : Array(String)?

        # The specific value of the cost category.

        @[JSON::Field(key: "Values")]
        getter values : Array(String)?

        def initialize(
          @key : String? = nil,
          @match_options : Array(String)? = nil,
          @values : Array(String)? = nil
        )
        end
      end

      # The types of cost that are included in a COST budget, such as tax and subscriptions. USAGE ,
      # RI_UTILIZATION , RI_COVERAGE , SAVINGS_PLANS_UTILIZATION , and SAVINGS_PLANS_COVERAGE budgets don't
      # have CostTypes .

      struct CostTypes
        include JSON::Serializable

        # Specifies whether a budget includes credits. The default value is true .

        @[JSON::Field(key: "IncludeCredit")]
        getter include_credit : Bool?

        # Specifies whether a budget includes discounts. The default value is true .

        @[JSON::Field(key: "IncludeDiscount")]
        getter include_discount : Bool?

        # Specifies whether a budget includes non-RI subscription costs. The default value is true .

        @[JSON::Field(key: "IncludeOtherSubscription")]
        getter include_other_subscription : Bool?

        # Specifies whether a budget includes recurring fees such as monthly RI fees. The default value is
        # true .

        @[JSON::Field(key: "IncludeRecurring")]
        getter include_recurring : Bool?

        # Specifies whether a budget includes refunds. The default value is true .

        @[JSON::Field(key: "IncludeRefund")]
        getter include_refund : Bool?

        # Specifies whether a budget includes subscriptions. The default value is true .

        @[JSON::Field(key: "IncludeSubscription")]
        getter include_subscription : Bool?

        # Specifies whether a budget includes support subscription fees. The default value is true .

        @[JSON::Field(key: "IncludeSupport")]
        getter include_support : Bool?

        # Specifies whether a budget includes taxes. The default value is true .

        @[JSON::Field(key: "IncludeTax")]
        getter include_tax : Bool?

        # Specifies whether a budget includes upfront RI costs. The default value is true .

        @[JSON::Field(key: "IncludeUpfront")]
        getter include_upfront : Bool?

        # Specifies whether a budget uses the amortized rate. The default value is false .

        @[JSON::Field(key: "UseAmortized")]
        getter use_amortized : Bool?

        # Specifies whether a budget uses a blended rate. The default value is false .

        @[JSON::Field(key: "UseBlended")]
        getter use_blended : Bool?

        def initialize(
          @include_credit : Bool? = nil,
          @include_discount : Bool? = nil,
          @include_other_subscription : Bool? = nil,
          @include_recurring : Bool? = nil,
          @include_refund : Bool? = nil,
          @include_subscription : Bool? = nil,
          @include_support : Bool? = nil,
          @include_tax : Bool? = nil,
          @include_upfront : Bool? = nil,
          @use_amortized : Bool? = nil,
          @use_blended : Bool? = nil
        )
        end
      end


      struct CreateBudgetActionRequest
        include JSON::Serializable


        @[JSON::Field(key: "AccountId")]
        getter account_id : String


        @[JSON::Field(key: "ActionThreshold")]
        getter action_threshold : Types::ActionThreshold

        # The type of action. This defines the type of tasks that can be carried out by this action. This
        # field also determines the format for definition.

        @[JSON::Field(key: "ActionType")]
        getter action_type : String

        # This specifies if the action needs manual or automatic approval.

        @[JSON::Field(key: "ApprovalModel")]
        getter approval_model : String


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String


        @[JSON::Field(key: "Definition")]
        getter definition : Types::Definition

        # The role passed for action execution and reversion. Roles and actions must be in the same account.

        @[JSON::Field(key: "ExecutionRoleArn")]
        getter execution_role_arn : String


        @[JSON::Field(key: "NotificationType")]
        getter notification_type : String


        @[JSON::Field(key: "Subscribers")]
        getter subscribers : Array(Types::Subscriber)

        # An optional list of tags to associate with the specified budget action. Each tag consists of a key
        # and a value, and each key must be unique for the resource.

        @[JSON::Field(key: "ResourceTags")]
        getter resource_tags : Array(Types::ResourceTag)?

        def initialize(
          @account_id : String,
          @action_threshold : Types::ActionThreshold,
          @action_type : String,
          @approval_model : String,
          @budget_name : String,
          @definition : Types::Definition,
          @execution_role_arn : String,
          @notification_type : String,
          @subscribers : Array(Types::Subscriber),
          @resource_tags : Array(Types::ResourceTag)? = nil
        )
        end
      end


      struct CreateBudgetActionResponse
        include JSON::Serializable


        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # A system-generated universally unique identifier (UUID) for the action.

        @[JSON::Field(key: "ActionId")]
        getter action_id : String


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        def initialize(
          @account_id : String,
          @action_id : String,
          @budget_name : String
        )
        end
      end

      # Request of CreateBudget

      struct CreateBudgetRequest
        include JSON::Serializable

        # The accountId that is associated with the budget.

        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # The budget object that you want to create.

        @[JSON::Field(key: "Budget")]
        getter budget : Types::Budget

        # A notification that you want to associate with a budget. A budget can have up to five notifications,
        # and each notification can have one SNS subscriber and up to 10 email subscribers. If you include
        # notifications and subscribers in your CreateBudget call, Amazon Web Services creates the
        # notifications and subscribers for you.

        @[JSON::Field(key: "NotificationsWithSubscribers")]
        getter notifications_with_subscribers : Array(Types::NotificationWithSubscribers)?

        # An optional list of tags to associate with the specified budget. Each tag consists of a key and a
        # value, and each key must be unique for the resource.

        @[JSON::Field(key: "ResourceTags")]
        getter resource_tags : Array(Types::ResourceTag)?

        def initialize(
          @account_id : String,
          @budget : Types::Budget,
          @notifications_with_subscribers : Array(Types::NotificationWithSubscribers)? = nil,
          @resource_tags : Array(Types::ResourceTag)? = nil
        )
        end
      end

      # Response of CreateBudget

      struct CreateBudgetResponse
        include JSON::Serializable

        def initialize
        end
      end

      # Request of CreateNotification

      struct CreateNotificationRequest
        include JSON::Serializable

        # The accountId that is associated with the budget that you want to create a notification for.

        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # The name of the budget that you want Amazon Web Services to notify you about. Budget names must be
        # unique within an account.

        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        # The notification that you want to create.

        @[JSON::Field(key: "Notification")]
        getter notification : Types::Notification

        # A list of subscribers that you want to associate with the notification. Each notification can have
        # one SNS subscriber and up to 10 email subscribers.

        @[JSON::Field(key: "Subscribers")]
        getter subscribers : Array(Types::Subscriber)

        def initialize(
          @account_id : String,
          @budget_name : String,
          @notification : Types::Notification,
          @subscribers : Array(Types::Subscriber)
        )
        end
      end

      # Response of CreateNotification

      struct CreateNotificationResponse
        include JSON::Serializable

        def initialize
        end
      end

      # Request of CreateSubscriber

      struct CreateSubscriberRequest
        include JSON::Serializable

        # The accountId that is associated with the budget that you want to create a subscriber for.

        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # The name of the budget that you want to subscribe to. Budget names must be unique within an account.

        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        # The notification that you want to create a subscriber for.

        @[JSON::Field(key: "Notification")]
        getter notification : Types::Notification

        # The subscriber that you want to associate with a budget notification.

        @[JSON::Field(key: "Subscriber")]
        getter subscriber : Types::Subscriber

        def initialize(
          @account_id : String,
          @budget_name : String,
          @notification : Types::Notification,
          @subscriber : Types::Subscriber
        )
        end
      end

      # Response of CreateSubscriber

      struct CreateSubscriberResponse
        include JSON::Serializable

        def initialize
        end
      end

      # You've exceeded the notification or subscriber limit.

      struct CreationLimitExceededException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # Specifies all of the type-specific parameters.

      struct Definition
        include JSON::Serializable

        # The Identity and Access Management (IAM) action definition details.

        @[JSON::Field(key: "IamActionDefinition")]
        getter iam_action_definition : Types::IamActionDefinition?

        # The service control policies (SCPs) action definition details.

        @[JSON::Field(key: "ScpActionDefinition")]
        getter scp_action_definition : Types::ScpActionDefinition?

        # The Amazon Web Services Systems Manager (SSM) action definition details.

        @[JSON::Field(key: "SsmActionDefinition")]
        getter ssm_action_definition : Types::SsmActionDefinition?

        def initialize(
          @iam_action_definition : Types::IamActionDefinition? = nil,
          @scp_action_definition : Types::ScpActionDefinition? = nil,
          @ssm_action_definition : Types::SsmActionDefinition? = nil
        )
        end
      end


      struct DeleteBudgetActionRequest
        include JSON::Serializable


        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # A system-generated universally unique identifier (UUID) for the action.

        @[JSON::Field(key: "ActionId")]
        getter action_id : String


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        def initialize(
          @account_id : String,
          @action_id : String,
          @budget_name : String
        )
        end
      end


      struct DeleteBudgetActionResponse
        include JSON::Serializable


        @[JSON::Field(key: "AccountId")]
        getter account_id : String


        @[JSON::Field(key: "Action")]
        getter action : Types::Action


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        def initialize(
          @account_id : String,
          @action : Types::Action,
          @budget_name : String
        )
        end
      end

      # Request of DeleteBudget

      struct DeleteBudgetRequest
        include JSON::Serializable

        # The accountId that is associated with the budget that you want to delete.

        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # The name of the budget that you want to delete.

        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        def initialize(
          @account_id : String,
          @budget_name : String
        )
        end
      end

      # Response of DeleteBudget

      struct DeleteBudgetResponse
        include JSON::Serializable

        def initialize
        end
      end

      # Request of DeleteNotification

      struct DeleteNotificationRequest
        include JSON::Serializable

        # The accountId that is associated with the budget whose notification you want to delete.

        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # The name of the budget whose notification you want to delete.

        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        # The notification that you want to delete.

        @[JSON::Field(key: "Notification")]
        getter notification : Types::Notification

        def initialize(
          @account_id : String,
          @budget_name : String,
          @notification : Types::Notification
        )
        end
      end

      # Response of DeleteNotification

      struct DeleteNotificationResponse
        include JSON::Serializable

        def initialize
        end
      end

      # Request of DeleteSubscriber

      struct DeleteSubscriberRequest
        include JSON::Serializable

        # The accountId that is associated with the budget whose subscriber you want to delete.

        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # The name of the budget whose subscriber you want to delete.

        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        # The notification whose subscriber you want to delete.

        @[JSON::Field(key: "Notification")]
        getter notification : Types::Notification

        # The subscriber that you want to delete.

        @[JSON::Field(key: "Subscriber")]
        getter subscriber : Types::Subscriber

        def initialize(
          @account_id : String,
          @budget_name : String,
          @notification : Types::Notification,
          @subscriber : Types::Subscriber
        )
        end
      end

      # Response of DeleteSubscriber

      struct DeleteSubscriberResponse
        include JSON::Serializable

        def initialize
        end
      end


      struct DescribeBudgetActionHistoriesRequest
        include JSON::Serializable


        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # A system-generated universally unique identifier (UUID) for the action.

        @[JSON::Field(key: "ActionId")]
        getter action_id : String


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String


        @[JSON::Field(key: "MaxResults")]
        getter max_results : Int32?


        @[JSON::Field(key: "NextToken")]
        getter next_token : String?


        @[JSON::Field(key: "TimePeriod")]
        getter time_period : Types::TimePeriod?

        def initialize(
          @account_id : String,
          @action_id : String,
          @budget_name : String,
          @max_results : Int32? = nil,
          @next_token : String? = nil,
          @time_period : Types::TimePeriod? = nil
        )
        end
      end


      struct DescribeBudgetActionHistoriesResponse
        include JSON::Serializable

        # The historical record of the budget action resource.

        @[JSON::Field(key: "ActionHistories")]
        getter action_histories : Array(Types::ActionHistory)


        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @action_histories : Array(Types::ActionHistory),
          @next_token : String? = nil
        )
        end
      end


      struct DescribeBudgetActionRequest
        include JSON::Serializable


        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # A system-generated universally unique identifier (UUID) for the action.

        @[JSON::Field(key: "ActionId")]
        getter action_id : String


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        def initialize(
          @account_id : String,
          @action_id : String,
          @budget_name : String
        )
        end
      end


      struct DescribeBudgetActionResponse
        include JSON::Serializable


        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # A budget action resource.

        @[JSON::Field(key: "Action")]
        getter action : Types::Action


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        def initialize(
          @account_id : String,
          @action : Types::Action,
          @budget_name : String
        )
        end
      end


      struct DescribeBudgetActionsForAccountRequest
        include JSON::Serializable


        @[JSON::Field(key: "AccountId")]
        getter account_id : String


        @[JSON::Field(key: "MaxResults")]
        getter max_results : Int32?


        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @account_id : String,
          @max_results : Int32? = nil,
          @next_token : String? = nil
        )
        end
      end


      struct DescribeBudgetActionsForAccountResponse
        include JSON::Serializable

        # A list of the budget action resources information.

        @[JSON::Field(key: "Actions")]
        getter actions : Array(Types::Action)


        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @actions : Array(Types::Action),
          @next_token : String? = nil
        )
        end
      end


      struct DescribeBudgetActionsForBudgetRequest
        include JSON::Serializable


        @[JSON::Field(key: "AccountId")]
        getter account_id : String


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String


        @[JSON::Field(key: "MaxResults")]
        getter max_results : Int32?


        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @account_id : String,
          @budget_name : String,
          @max_results : Int32? = nil,
          @next_token : String? = nil
        )
        end
      end


      struct DescribeBudgetActionsForBudgetResponse
        include JSON::Serializable

        # A list of the budget action resources information.

        @[JSON::Field(key: "Actions")]
        getter actions : Array(Types::Action)


        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @actions : Array(Types::Action),
          @next_token : String? = nil
        )
        end
      end


      struct DescribeBudgetNotificationsForAccountRequest
        include JSON::Serializable


        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # An integer that represents how many budgets a paginated response contains. The default is 50.

        @[JSON::Field(key: "MaxResults")]
        getter max_results : Int32?


        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @account_id : String,
          @max_results : Int32? = nil,
          @next_token : String? = nil
        )
        end
      end


      struct DescribeBudgetNotificationsForAccountResponse
        include JSON::Serializable

        # A list of budget names and associated notifications for an account.

        @[JSON::Field(key: "BudgetNotificationsForAccount")]
        getter budget_notifications_for_account : Array(Types::BudgetNotificationsForAccount)?


        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @budget_notifications_for_account : Array(Types::BudgetNotificationsForAccount)? = nil,
          @next_token : String? = nil
        )
        end
      end


      struct DescribeBudgetPerformanceHistoryRequest
        include JSON::Serializable


        @[JSON::Field(key: "AccountId")]
        getter account_id : String


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String


        @[JSON::Field(key: "MaxResults")]
        getter max_results : Int32?


        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        # Retrieves how often the budget went into an ALARM state for the specified time period.

        @[JSON::Field(key: "TimePeriod")]
        getter time_period : Types::TimePeriod?

        def initialize(
          @account_id : String,
          @budget_name : String,
          @max_results : Int32? = nil,
          @next_token : String? = nil,
          @time_period : Types::TimePeriod? = nil
        )
        end
      end


      struct DescribeBudgetPerformanceHistoryResponse
        include JSON::Serializable

        # The history of how often the budget has gone into an ALARM state. For DAILY budgets, the history
        # saves the state of the budget for the last 60 days. For MONTHLY budgets, the history saves the state
        # of the budget for the current month plus the last 12 months. For QUARTERLY budgets, the history
        # saves the state of the budget for the last four quarters.

        @[JSON::Field(key: "BudgetPerformanceHistory")]
        getter budget_performance_history : Types::BudgetPerformanceHistory?


        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @budget_performance_history : Types::BudgetPerformanceHistory? = nil,
          @next_token : String? = nil
        )
        end
      end

      # Request of DescribeBudget

      struct DescribeBudgetRequest
        include JSON::Serializable

        # The accountId that is associated with the budget that you want a description of.

        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # The name of the budget that you want a description of.

        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        # Specifies whether the response includes the filter expression associated with the budget. By showing
        # the filter expression, you can see detailed filtering logic applied to the budget, such as Amazon
        # Web Services services or tags that are being tracked.

        @[JSON::Field(key: "ShowFilterExpression")]
        getter show_filter_expression : Bool?

        def initialize(
          @account_id : String,
          @budget_name : String,
          @show_filter_expression : Bool? = nil
        )
        end
      end

      # Response of DescribeBudget

      struct DescribeBudgetResponse
        include JSON::Serializable

        # The description of the budget.

        @[JSON::Field(key: "Budget")]
        getter budget : Types::Budget?

        def initialize(
          @budget : Types::Budget? = nil
        )
        end
      end

      # Request of DescribeBudgets

      struct DescribeBudgetsRequest
        include JSON::Serializable

        # The accountId that is associated with the budgets that you want to describe.

        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # An integer that represents how many budgets a paginated response contains. The default is 100.

        @[JSON::Field(key: "MaxResults")]
        getter max_results : Int32?

        # The pagination token that you include in your request to indicate the next set of results that you
        # want to retrieve.

        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        # Specifies whether the response includes the filter expression associated with the budgets. By
        # showing the filter expression, you can see detailed filtering logic applied to the budgets, such as
        # Amazon Web Services services or tags that are being tracked.

        @[JSON::Field(key: "ShowFilterExpression")]
        getter show_filter_expression : Bool?

        def initialize(
          @account_id : String,
          @max_results : Int32? = nil,
          @next_token : String? = nil,
          @show_filter_expression : Bool? = nil
        )
        end
      end

      # Response of DescribeBudgets

      struct DescribeBudgetsResponse
        include JSON::Serializable

        # A list of budgets.

        @[JSON::Field(key: "Budgets")]
        getter budgets : Array(Types::Budget)?

        # The pagination token in the service response that indicates the next set of results that you can
        # retrieve.

        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @budgets : Array(Types::Budget)? = nil,
          @next_token : String? = nil
        )
        end
      end

      # Request of DescribeNotificationsForBudget

      struct DescribeNotificationsForBudgetRequest
        include JSON::Serializable

        # The accountId that is associated with the budget whose notifications you want descriptions of.

        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # The name of the budget whose notifications you want descriptions of.

        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        # An optional integer that represents how many entries a paginated response contains.

        @[JSON::Field(key: "MaxResults")]
        getter max_results : Int32?

        # The pagination token that you include in your request to indicate the next set of results that you
        # want to retrieve.

        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @account_id : String,
          @budget_name : String,
          @max_results : Int32? = nil,
          @next_token : String? = nil
        )
        end
      end

      # Response of GetNotificationsForBudget

      struct DescribeNotificationsForBudgetResponse
        include JSON::Serializable

        # The pagination token in the service response that indicates the next set of results that you can
        # retrieve.

        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        # A list of notifications that are associated with a budget.

        @[JSON::Field(key: "Notifications")]
        getter notifications : Array(Types::Notification)?

        def initialize(
          @next_token : String? = nil,
          @notifications : Array(Types::Notification)? = nil
        )
        end
      end

      # Request of DescribeSubscribersForNotification

      struct DescribeSubscribersForNotificationRequest
        include JSON::Serializable

        # The accountId that is associated with the budget whose subscribers you want descriptions of.

        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # The name of the budget whose subscribers you want descriptions of.

        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        # The notification whose subscribers you want to list.

        @[JSON::Field(key: "Notification")]
        getter notification : Types::Notification

        # An optional integer that represents how many entries a paginated response contains.

        @[JSON::Field(key: "MaxResults")]
        getter max_results : Int32?

        # The pagination token that you include in your request to indicate the next set of results that you
        # want to retrieve.

        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @account_id : String,
          @budget_name : String,
          @notification : Types::Notification,
          @max_results : Int32? = nil,
          @next_token : String? = nil
        )
        end
      end

      # Response of DescribeSubscribersForNotification

      struct DescribeSubscribersForNotificationResponse
        include JSON::Serializable

        # The pagination token in the service response that indicates the next set of results that you can
        # retrieve.

        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        # A list of subscribers that are associated with a notification.

        @[JSON::Field(key: "Subscribers")]
        getter subscribers : Array(Types::Subscriber)?

        def initialize(
          @next_token : String? = nil,
          @subscribers : Array(Types::Subscriber)? = nil
        )
        end
      end

      # The budget name already exists. Budget names must be unique within an account.

      struct DuplicateRecordException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end


      struct ExecuteBudgetActionRequest
        include JSON::Serializable


        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # A system-generated universally unique identifier (UUID) for the action.

        @[JSON::Field(key: "ActionId")]
        getter action_id : String


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        # The type of execution.

        @[JSON::Field(key: "ExecutionType")]
        getter execution_type : String

        def initialize(
          @account_id : String,
          @action_id : String,
          @budget_name : String,
          @execution_type : String
        )
        end
      end


      struct ExecuteBudgetActionResponse
        include JSON::Serializable


        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # A system-generated universally unique identifier (UUID) for the action.

        @[JSON::Field(key: "ActionId")]
        getter action_id : String


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        # The type of execution.

        @[JSON::Field(key: "ExecutionType")]
        getter execution_type : String

        def initialize(
          @account_id : String,
          @action_id : String,
          @budget_name : String,
          @execution_type : String
        )
        end
      end

      # The pagination token expired.

      struct ExpiredNextTokenException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # Use Expression to filter in various Budgets APIs.

      struct Expression
        include JSON::Serializable

        # Return results that match both Dimension objects.

        @[JSON::Field(key: "And")]
        getter and : Array(Types::Expression)?

        # The filter that's based on CostCategoryValues.

        @[JSON::Field(key: "CostCategories")]
        getter cost_categories : Types::CostCategoryValues?

        # The specific Dimension to use for Expression.

        @[JSON::Field(key: "Dimensions")]
        getter dimensions : Types::ExpressionDimensionValues?

        # Return results that don't match a Dimension object.

        @[JSON::Field(key: "Not")]
        getter not : Types::Expression?

        # Return results that match either Dimension object.

        @[JSON::Field(key: "Or")]
        getter or : Array(Types::Expression)?

        # The specific Tag to use for Expression.

        @[JSON::Field(key: "Tags")]
        getter tags : Types::TagValues?

        def initialize(
          @and : Array(Types::Expression)? = nil,
          @cost_categories : Types::CostCategoryValues? = nil,
          @dimensions : Types::ExpressionDimensionValues? = nil,
          @not : Types::Expression? = nil,
          @or : Array(Types::Expression)? = nil,
          @tags : Types::TagValues? = nil
        )
        end
      end

      # Contains the specifications for the filters to use for your request.

      struct ExpressionDimensionValues
        include JSON::Serializable

        # The name of the dimension that you want to filter on.

        @[JSON::Field(key: "Key")]
        getter key : String

        # The metadata values you can specify to filter upon, so that the results all match at least one of
        # the specified values.

        @[JSON::Field(key: "Values")]
        getter values : Array(String)

        # The match options that you can use to filter your results. You can specify only one of these values
        # in the array.

        @[JSON::Field(key: "MatchOptions")]
        getter match_options : Array(String)?

        def initialize(
          @key : String,
          @values : Array(String),
          @match_options : Array(String)? = nil
        )
        end
      end

      # Provides information about the current operational state of a billing view resource, including its
      # ability to access and update based on its associated billing view.

      struct HealthStatus
        include JSON::Serializable


        @[JSON::Field(key: "LastUpdatedTime", converter: AwsSdk::Runtime::UnixTimestampConverter)]
        getter last_updated_time : Time?

        # The current status of the billing view resource.

        @[JSON::Field(key: "Status")]
        getter status : String?

        # The reason for the current status. BILLING_VIEW_NO_ACCESS : The billing view resource does not grant
        # billing:GetBillingViewData permission to this account. BILLING_VIEW_UNHEALTHY : The billing view
        # associated with the budget is unhealthy. FILTER_INVALID : The filter contains reference to an
        # account you do not have access to. MULTI_YEAR_HISTORICAL_DATA_DISABLED : The budget is not being
        # updated. Enable multi-year historical data in your Cost Management preferences.

        @[JSON::Field(key: "StatusReason")]
        getter status_reason : String?

        def initialize(
          @last_updated_time : Time? = nil,
          @status : String? = nil,
          @status_reason : String? = nil
        )
        end
      end

      # The parameters that define or describe the historical data that your auto-adjusting budget is based
      # on.

      struct HistoricalOptions
        include JSON::Serializable

        # The number of budget periods included in the moving-average calculation that determines your
        # auto-adjusted budget amount. The maximum value depends on the TimeUnit granularity of the budget:
        # For the DAILY granularity, the maximum value is 60 . For the MONTHLY granularity, the maximum value
        # is 12 . For the QUARTERLY granularity, the maximum value is 4 . For the ANNUALLY granularity, the
        # maximum value is 1 .

        @[JSON::Field(key: "BudgetAdjustmentPeriod")]
        getter budget_adjustment_period : Int32

        # The integer that describes how many budget periods in your BudgetAdjustmentPeriod are included in
        # the calculation of your current BudgetLimit . If the first budget period in your
        # BudgetAdjustmentPeriod has no cost data, then that budget period isn’t included in the average that
        # determines your budget limit. For example, if you set BudgetAdjustmentPeriod as 4 quarters, but your
        # account had no cost data in the first quarter, then only the last three quarters are included in the
        # calculation. In this scenario, LookBackAvailablePeriods returns 3 . You can’t set your own
        # LookBackAvailablePeriods . The value is automatically calculated from the BudgetAdjustmentPeriod and
        # your historical cost data.

        @[JSON::Field(key: "LookBackAvailablePeriods")]
        getter look_back_available_periods : Int32?

        def initialize(
          @budget_adjustment_period : Int32,
          @look_back_available_periods : Int32? = nil
        )
        end
      end

      # The Identity and Access Management (IAM) action definition details.

      struct IamActionDefinition
        include JSON::Serializable

        # The Amazon Resource Name (ARN) of the policy to be attached.

        @[JSON::Field(key: "PolicyArn")]
        getter policy_arn : String

        # A list of groups to be attached. There must be at least one group.

        @[JSON::Field(key: "Groups")]
        getter groups : Array(String)?

        # A list of roles to be attached. There must be at least one role.

        @[JSON::Field(key: "Roles")]
        getter roles : Array(String)?

        # A list of users to be attached. There must be at least one user.

        @[JSON::Field(key: "Users")]
        getter users : Array(String)?

        def initialize(
          @policy_arn : String,
          @groups : Array(String)? = nil,
          @roles : Array(String)? = nil,
          @users : Array(String)? = nil
        )
        end
      end

      # An error on the server occurred during the processing of your request. Try again later.

      struct InternalErrorException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # The pagination token is invalid.

      struct InvalidNextTokenException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # An error on the client occurred. Typically, the cause is an invalid input value.

      struct InvalidParameterException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end


      struct ListTagsForResourceRequest
        include JSON::Serializable

        # The unique identifier for the resource.

        @[JSON::Field(key: "ResourceARN")]
        getter resource_arn : String

        def initialize(
          @resource_arn : String
        )
        end
      end


      struct ListTagsForResourceResponse
        include JSON::Serializable

        # The tags associated with the resource.

        @[JSON::Field(key: "ResourceTags")]
        getter resource_tags : Array(Types::ResourceTag)?

        def initialize(
          @resource_tags : Array(Types::ResourceTag)? = nil
        )
        end
      end

      # We can’t locate the resource that you specified.

      struct NotFoundException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # A notification that's associated with a budget. A budget can have up to ten notifications. Each
      # notification must have at least one subscriber. A notification can have one SNS subscriber and up to
      # 10 email subscribers, for a total of 11 subscribers. For example, if you have a budget for 200
      # dollars and you want to be notified when you go over 160 dollars, create a notification with the
      # following parameters: A notificationType of ACTUAL A thresholdType of PERCENTAGE A
      # comparisonOperator of GREATER_THAN A notification threshold of 80

      struct Notification
        include JSON::Serializable

        # The comparison that's used for this notification.

        @[JSON::Field(key: "ComparisonOperator")]
        getter comparison_operator : String

        # Specifies whether the notification is for how much you have spent ( ACTUAL ) or for how much that
        # you're forecasted to spend ( FORECASTED ).

        @[JSON::Field(key: "NotificationType")]
        getter notification_type : String

        # The threshold that's associated with a notification. Thresholds are always a percentage, and many
        # customers find value being alerted between 50% - 200% of the budgeted amount. The maximum limit for
        # your threshold is 1,000,000% above the budgeted amount.

        @[JSON::Field(key: "Threshold")]
        getter threshold : Float64

        # Specifies whether this notification is in alarm. If a budget notification is in the ALARM state, you
        # passed the set threshold for the budget.

        @[JSON::Field(key: "NotificationState")]
        getter notification_state : String?

        # The type of threshold for a notification. For ABSOLUTE_VALUE thresholds, Amazon Web Services
        # notifies you when you go over or are forecasted to go over your total cost threshold. For PERCENTAGE
        # thresholds, Amazon Web Services notifies you when you go over or are forecasted to go over a certain
        # percentage of your forecasted spend. For example, if you have a budget for 200 dollars and you have
        # a PERCENTAGE threshold of 80%, Amazon Web Services notifies you when you go over 160 dollars.

        @[JSON::Field(key: "ThresholdType")]
        getter threshold_type : String?

        def initialize(
          @comparison_operator : String,
          @notification_type : String,
          @threshold : Float64,
          @notification_state : String? = nil,
          @threshold_type : String? = nil
        )
        end
      end

      # A notification with subscribers. A notification can have one SNS subscriber and up to 10 email
      # subscribers, for a total of 11 subscribers.

      struct NotificationWithSubscribers
        include JSON::Serializable

        # The notification that's associated with a budget.

        @[JSON::Field(key: "Notification")]
        getter notification : Types::Notification

        # A list of subscribers who are subscribed to this notification.

        @[JSON::Field(key: "Subscribers")]
        getter subscribers : Array(Types::Subscriber)

        def initialize(
          @notification : Types::Notification,
          @subscribers : Array(Types::Subscriber)
        )
        end
      end

      # The request was received and recognized by the server, but the server rejected that particular
      # method for the requested resource.

      struct ResourceLockedException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # The tag structure that contains a tag key and value.

      struct ResourceTag
        include JSON::Serializable

        # The key that's associated with the tag.

        @[JSON::Field(key: "Key")]
        getter key : String

        # The value that's associated with the tag.

        @[JSON::Field(key: "Value")]
        getter value : String

        def initialize(
          @key : String,
          @value : String
        )
        end
      end

      # The service control policies (SCP) action definition details.

      struct ScpActionDefinition
        include JSON::Serializable

        # The policy ID attached.

        @[JSON::Field(key: "PolicyId")]
        getter policy_id : String

        # A list of target IDs.

        @[JSON::Field(key: "TargetIds")]
        getter target_ids : Array(String)

        def initialize(
          @policy_id : String,
          @target_ids : Array(String)
        )
        end
      end

      # You've reached a Service Quota limit on this resource.

      struct ServiceQuotaExceededException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # The amount of cost or usage that's measured for a budget. Cost example: A Spend for 3 USD of costs
      # has the following parameters: An Amount of 3 A Unit of USD Usage example: A Spend for 3 GB of S3
      # usage has the following parameters: An Amount of 3 A Unit of GB

      struct Spend
        include JSON::Serializable

        # The cost or usage amount that's associated with a budget forecast, actual spend, or budget
        # threshold.

        @[JSON::Field(key: "Amount")]
        getter amount : String

        # The unit of measurement that's used for the budget forecast, actual spend, or budget threshold.

        @[JSON::Field(key: "Unit")]
        getter unit : String

        def initialize(
          @amount : String,
          @unit : String
        )
        end
      end

      # The Amazon Web Services Systems Manager (SSM) action definition details.

      struct SsmActionDefinition
        include JSON::Serializable

        # The action subType.

        @[JSON::Field(key: "ActionSubType")]
        getter action_sub_type : String

        # The EC2 and RDS instance IDs.

        @[JSON::Field(key: "InstanceIds")]
        getter instance_ids : Array(String)

        # The Region to run the SSM document.

        @[JSON::Field(key: "Region")]
        getter region : String

        def initialize(
          @action_sub_type : String,
          @instance_ids : Array(String),
          @region : String
        )
        end
      end

      # The subscriber to a budget notification. The subscriber consists of a subscription type and either
      # an Amazon SNS topic or an email address. For example, an email subscriber has the following
      # parameters: A subscriptionType of EMAIL An address of example@example.com

      struct Subscriber
        include JSON::Serializable

        # The address that Amazon Web Services sends budget notifications to, either an SNS topic or an email.
        # When you create a subscriber, the value of Address can't contain line breaks.

        @[JSON::Field(key: "Address")]
        getter address : String

        # The type of notification that Amazon Web Services sends to a subscriber.

        @[JSON::Field(key: "SubscriptionType")]
        getter subscription_type : String

        def initialize(
          @address : String,
          @subscription_type : String
        )
        end
      end


      struct TagResourceRequest
        include JSON::Serializable

        # The unique identifier for the resource.

        @[JSON::Field(key: "ResourceARN")]
        getter resource_arn : String

        # The tags associated with the resource.

        @[JSON::Field(key: "ResourceTags")]
        getter resource_tags : Array(Types::ResourceTag)

        def initialize(
          @resource_arn : String,
          @resource_tags : Array(Types::ResourceTag)
        )
        end
      end


      struct TagResourceResponse
        include JSON::Serializable

        def initialize
        end
      end

      # The values that are available for a tag.

      struct TagValues
        include JSON::Serializable

        # The key for the tag.

        @[JSON::Field(key: "Key")]
        getter key : String?

        # The match options that you can use to filter your results.

        @[JSON::Field(key: "MatchOptions")]
        getter match_options : Array(String)?

        # The specific value of the tag.

        @[JSON::Field(key: "Values")]
        getter values : Array(String)?

        def initialize(
          @key : String? = nil,
          @match_options : Array(String)? = nil,
          @values : Array(String)? = nil
        )
        end
      end

      # The number of API requests has exceeded the maximum allowed API request throttling limit for the
      # account.

      struct ThrottlingException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        def initialize(
          @message : String? = nil
        )
        end
      end

      # The period of time that's covered by a budget. The period has a start date and an end date. The
      # start date must come before the end date. There are no restrictions on the end date.

      struct TimePeriod
        include JSON::Serializable

        # The end date for a budget. If you didn't specify an end date, Amazon Web Services set your end date
        # to 06/15/87 00:00 UTC . The defaults are the same for the Billing and Cost Management console and
        # the API. After the end date, Amazon Web Services deletes the budget and all the associated
        # notifications and subscribers. You can change your end date with the UpdateBudget operation.

        @[JSON::Field(key: "End", converter: AwsSdk::Runtime::UnixTimestampConverter)]
        getter end : Time?

        # The start date for a budget. If you created your budget and didn't specify a start date, Amazon Web
        # Services defaults to the start of your chosen time period (DAILY, MONTHLY, QUARTERLY, ANNUALLY, or
        # CUSTOM). For example, if you created your budget on January 24, 2018, chose DAILY , and didn't set a
        # start date, Amazon Web Services set your start date to 01/24/18 00:00 UTC . If you chose MONTHLY ,
        # Amazon Web Services set your start date to 01/01/18 00:00 UTC . The defaults are the same for the
        # Billing and Cost Management console and the API. You can change your start date with the
        # UpdateBudget operation.

        @[JSON::Field(key: "Start", converter: AwsSdk::Runtime::UnixTimestampConverter)]
        getter start : Time?

        def initialize(
          @end : Time? = nil,
          @start : Time? = nil
        )
        end
      end


      struct UntagResourceRequest
        include JSON::Serializable

        # The unique identifier for the resource.

        @[JSON::Field(key: "ResourceARN")]
        getter resource_arn : String

        # The key that's associated with the tag.

        @[JSON::Field(key: "ResourceTagKeys")]
        getter resource_tag_keys : Array(String)

        def initialize(
          @resource_arn : String,
          @resource_tag_keys : Array(String)
        )
        end
      end


      struct UntagResourceResponse
        include JSON::Serializable

        def initialize
        end
      end


      struct UpdateBudgetActionRequest
        include JSON::Serializable


        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # A system-generated universally unique identifier (UUID) for the action.

        @[JSON::Field(key: "ActionId")]
        getter action_id : String


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String


        @[JSON::Field(key: "ActionThreshold")]
        getter action_threshold : Types::ActionThreshold?

        # This specifies if the action needs manual or automatic approval.

        @[JSON::Field(key: "ApprovalModel")]
        getter approval_model : String?


        @[JSON::Field(key: "Definition")]
        getter definition : Types::Definition?

        # The role passed for action execution and reversion. Roles and actions must be in the same account.

        @[JSON::Field(key: "ExecutionRoleArn")]
        getter execution_role_arn : String?


        @[JSON::Field(key: "NotificationType")]
        getter notification_type : String?


        @[JSON::Field(key: "Subscribers")]
        getter subscribers : Array(Types::Subscriber)?

        def initialize(
          @account_id : String,
          @action_id : String,
          @budget_name : String,
          @action_threshold : Types::ActionThreshold? = nil,
          @approval_model : String? = nil,
          @definition : Types::Definition? = nil,
          @execution_role_arn : String? = nil,
          @notification_type : String? = nil,
          @subscribers : Array(Types::Subscriber)? = nil
        )
        end
      end


      struct UpdateBudgetActionResponse
        include JSON::Serializable


        @[JSON::Field(key: "AccountId")]
        getter account_id : String


        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        # The updated action resource information.

        @[JSON::Field(key: "NewAction")]
        getter new_action : Types::Action

        # The previous action resource information.

        @[JSON::Field(key: "OldAction")]
        getter old_action : Types::Action

        def initialize(
          @account_id : String,
          @budget_name : String,
          @new_action : Types::Action,
          @old_action : Types::Action
        )
        end
      end

      # Request of UpdateBudget

      struct UpdateBudgetRequest
        include JSON::Serializable

        # The accountId that is associated with the budget that you want to update.

        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # The budget that you want to update your budget to.

        @[JSON::Field(key: "NewBudget")]
        getter new_budget : Types::Budget

        def initialize(
          @account_id : String,
          @new_budget : Types::Budget
        )
        end
      end

      # Response of UpdateBudget

      struct UpdateBudgetResponse
        include JSON::Serializable

        def initialize
        end
      end

      # Request of UpdateNotification

      struct UpdateNotificationRequest
        include JSON::Serializable

        # The accountId that is associated with the budget whose notification you want to update.

        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # The name of the budget whose notification you want to update.

        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        # The updated notification to be associated with a budget.

        @[JSON::Field(key: "NewNotification")]
        getter new_notification : Types::Notification

        # The previous notification that is associated with a budget.

        @[JSON::Field(key: "OldNotification")]
        getter old_notification : Types::Notification

        def initialize(
          @account_id : String,
          @budget_name : String,
          @new_notification : Types::Notification,
          @old_notification : Types::Notification
        )
        end
      end

      # Response of UpdateNotification

      struct UpdateNotificationResponse
        include JSON::Serializable

        def initialize
        end
      end

      # Request of UpdateSubscriber

      struct UpdateSubscriberRequest
        include JSON::Serializable

        # The accountId that is associated with the budget whose subscriber you want to update.

        @[JSON::Field(key: "AccountId")]
        getter account_id : String

        # The name of the budget whose subscriber you want to update.

        @[JSON::Field(key: "BudgetName")]
        getter budget_name : String

        # The updated subscriber that is associated with a budget notification.

        @[JSON::Field(key: "NewSubscriber")]
        getter new_subscriber : Types::Subscriber

        # The notification whose subscriber you want to update.

        @[JSON::Field(key: "Notification")]
        getter notification : Types::Notification

        # The previous subscriber that is associated with a budget notification.

        @[JSON::Field(key: "OldSubscriber")]
        getter old_subscriber : Types::Subscriber

        def initialize(
          @account_id : String,
          @budget_name : String,
          @new_subscriber : Types::Subscriber,
          @notification : Types::Notification,
          @old_subscriber : Types::Subscriber
        )
        end
      end

      # Response of UpdateSubscriber

      struct UpdateSubscriberResponse
        include JSON::Serializable

        def initialize
        end
      end
    end
  end
end
