module AwsSdk
  module Forecastquery
    class Client
      getter endpoint : String
      getter endpoint_headers : Hash(String, String)
      getter region : String
      getter credentials : AwsSdk::Runtime::Credentials
      getter transport : AwsSdk::Runtime::Transport
      getter runtime : AwsSdk::Runtime::Client

      def initialize(
        endpoint : String? = nil,
        region : String? = nil,
        credentials : AwsSdk::Runtime::Credentials? = nil,
        profile : String? = nil,
        use_fips : Bool? = nil,
        use_dualstack : Bool? = nil,
        transport : AwsSdk::Runtime::Transport = AwsSdk::Runtime::HttpTransport.new
      )
        @transport = transport
        @region = region || AwsSdk::Runtime::Defaults.resolve_region(profile, @transport)
        @credentials = credentials || AwsSdk::Runtime::Defaults.resolve_credentials(profile, @transport)
        endpoint_provider = AwsSdk::Runtime::EndpointProvider.new(Model::ENDPOINT_PREFIX, Model::ENDPOINT_RULE_SET_JSON)
        endpoint_result = endpoint_provider.resolve(@region, endpoint, use_fips, use_dualstack)
        @endpoint = endpoint_result.url
        @endpoint_headers = endpoint_result.headers
        @runtime = AwsSdk::Runtime::Client.new(@endpoint, @region, Model::SIGNING_NAME, @credentials, @transport, @endpoint_headers)
      end

      # Retrieves a forecast for a single item, filtered by the supplied criteria. The criteria is a
      # key-value pair. The key is either item_id (or the equivalent non-timestamp, non-target field) from
      # the TARGET_TIME_SERIES dataset, or one of the forecast dimensions specified as part of the
      # FeaturizationConfig object. By default, QueryForecast returns the complete date range for the
      # filtered forecast. You can request a specific date range. To get the full forecast, use the
      # CreateForecastExportJob operation. The forecasts generated by Amazon Forecast are in the same
      # timezone as the dataset that was used to create the predictor.
      def query_forecast(
        filters : Hash(String, String),
        forecast_arn : String,
        end_date : String? = nil,
        next_token : String? = nil,
        start_date : String? = nil
      ) : Types::QueryForecastResponse
        input = Types::QueryForecastRequest.new(filters: filters, forecast_arn: forecast_arn, end_date: end_date, next_token: next_token, start_date: start_date)
        query_forecast(input)
      end
      def query_forecast(input : Types::QueryForecastRequest) : Types::QueryForecastResponse
        request = Protocol::JsonRpc.build_request(Model::QUERY_FORECAST, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::QueryForecastResponse, "QueryForecast")
      end

      # Retrieves a what-if forecast.
      def query_what_if_forecast(
        filters : Hash(String, String),
        what_if_forecast_arn : String,
        end_date : String? = nil,
        next_token : String? = nil,
        start_date : String? = nil
      ) : Types::QueryWhatIfForecastResponse
        input = Types::QueryWhatIfForecastRequest.new(filters: filters, what_if_forecast_arn: what_if_forecast_arn, end_date: end_date, next_token: next_token, start_date: start_date)
        query_what_if_forecast(input)
      end
      def query_what_if_forecast(input : Types::QueryWhatIfForecastRequest) : Types::QueryWhatIfForecastResponse
        request = Protocol::JsonRpc.build_request(Model::QUERY_WHAT_IF_FORECAST, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::QueryWhatIfForecastResponse, "QueryWhatIfForecast")
      end
    end
  end
end
