module AwsSdk
  module Inspector
    class Client
      getter endpoint : String
      getter endpoint_headers : Hash(String, String)
      getter region : String
      getter credentials : AwsSdk::Runtime::Credentials
      getter transport : AwsSdk::Runtime::Transport
      getter runtime : AwsSdk::Runtime::Client

      def initialize(
        endpoint : String? = nil,
        region : String? = nil,
        credentials : AwsSdk::Runtime::Credentials? = nil,
        profile : String? = nil,
        use_fips : Bool? = nil,
        use_dualstack : Bool? = nil,
        transport : AwsSdk::Runtime::Transport = AwsSdk::Runtime::HttpTransport.new
      )
        @transport = transport
        @region = region || AwsSdk::Runtime::Defaults.resolve_region(profile, @transport)
        @credentials = credentials || AwsSdk::Runtime::Defaults.resolve_credentials(profile, @transport)
        endpoint_provider = AwsSdk::Runtime::EndpointProvider.new(Model::ENDPOINT_PREFIX, Model::ENDPOINT_RULE_SET_JSON)
        endpoint_result = endpoint_provider.resolve(@region, endpoint, use_fips, use_dualstack)
        @endpoint = endpoint_result.url
        @endpoint_headers = endpoint_result.headers
        @runtime = AwsSdk::Runtime::Client.new(@endpoint, @region, Model::SIGNING_NAME, @credentials, @transport, @endpoint_headers)
      end

      # Assigns attributes (key and value pairs) to the findings that are specified by the ARNs of the
      # findings.
      def add_attributes_to_findings(
        attributes : Array(Types::Attribute),
        finding_arns : Array(String)
      ) : Types::AddAttributesToFindingsResponse
        input = Types::AddAttributesToFindingsRequest.new(attributes: attributes, finding_arns: finding_arns)
        add_attributes_to_findings(input)
      end
      def add_attributes_to_findings(input : Types::AddAttributesToFindingsRequest) : Types::AddAttributesToFindingsResponse
        request = Protocol::JsonRpc.build_request(Model::ADD_ATTRIBUTES_TO_FINDINGS, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::AddAttributesToFindingsResponse, "AddAttributesToFindings")
      end

      # Creates a new assessment target using the ARN of the resource group that is generated by
      # CreateResourceGroup . If resourceGroupArn is not specified, all EC2 instances in the current AWS
      # account and region are included in the assessment target. If the service-linked role isn’t already
      # registered, this action also creates and registers a service-linked role to grant Amazon Inspector
      # access to AWS Services needed to perform security assessments. You can create up to 50 assessment
      # targets per AWS account. You can run up to 500 concurrent agents per AWS account. For more
      # information, see Amazon Inspector Assessment Targets .
      def create_assessment_target(
        assessment_target_name : String,
        resource_group_arn : String? = nil
      ) : Types::CreateAssessmentTargetResponse
        input = Types::CreateAssessmentTargetRequest.new(assessment_target_name: assessment_target_name, resource_group_arn: resource_group_arn)
        create_assessment_target(input)
      end
      def create_assessment_target(input : Types::CreateAssessmentTargetRequest) : Types::CreateAssessmentTargetResponse
        request = Protocol::JsonRpc.build_request(Model::CREATE_ASSESSMENT_TARGET, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::CreateAssessmentTargetResponse, "CreateAssessmentTarget")
      end

      # Creates an assessment template for the assessment target that is specified by the ARN of the
      # assessment target. If the service-linked role isn’t already registered, this action also creates and
      # registers a service-linked role to grant Amazon Inspector access to AWS Services needed to perform
      # security assessments.
      def create_assessment_template(
        assessment_target_arn : String,
        assessment_template_name : String,
        duration_in_seconds : Int32,
        rules_package_arns : Array(String),
        user_attributes_for_findings : Array(Types::Attribute)? = nil
      ) : Types::CreateAssessmentTemplateResponse
        input = Types::CreateAssessmentTemplateRequest.new(assessment_target_arn: assessment_target_arn, assessment_template_name: assessment_template_name, duration_in_seconds: duration_in_seconds, rules_package_arns: rules_package_arns, user_attributes_for_findings: user_attributes_for_findings)
        create_assessment_template(input)
      end
      def create_assessment_template(input : Types::CreateAssessmentTemplateRequest) : Types::CreateAssessmentTemplateResponse
        request = Protocol::JsonRpc.build_request(Model::CREATE_ASSESSMENT_TEMPLATE, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::CreateAssessmentTemplateResponse, "CreateAssessmentTemplate")
      end

      # Starts the generation of an exclusions preview for the specified assessment template. The exclusions
      # preview lists the potential exclusions (ExclusionPreview) that Inspector can detect before it runs
      # the assessment.
      def create_exclusions_preview(
        assessment_template_arn : String
      ) : Types::CreateExclusionsPreviewResponse
        input = Types::CreateExclusionsPreviewRequest.new(assessment_template_arn: assessment_template_arn)
        create_exclusions_preview(input)
      end
      def create_exclusions_preview(input : Types::CreateExclusionsPreviewRequest) : Types::CreateExclusionsPreviewResponse
        request = Protocol::JsonRpc.build_request(Model::CREATE_EXCLUSIONS_PREVIEW, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::CreateExclusionsPreviewResponse, "CreateExclusionsPreview")
      end

      # Creates a resource group using the specified set of tags (key and value pairs) that are used to
      # select the EC2 instances to be included in an Amazon Inspector assessment target. The created
      # resource group is then used to create an Amazon Inspector assessment target. For more information,
      # see CreateAssessmentTarget .
      def create_resource_group(
        resource_group_tags : Array(Types::ResourceGroupTag)
      ) : Types::CreateResourceGroupResponse
        input = Types::CreateResourceGroupRequest.new(resource_group_tags: resource_group_tags)
        create_resource_group(input)
      end
      def create_resource_group(input : Types::CreateResourceGroupRequest) : Types::CreateResourceGroupResponse
        request = Protocol::JsonRpc.build_request(Model::CREATE_RESOURCE_GROUP, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::CreateResourceGroupResponse, "CreateResourceGroup")
      end

      # Deletes the assessment run that is specified by the ARN of the assessment run.
      def delete_assessment_run(
        assessment_run_arn : String
      ) : Nil
        input = Types::DeleteAssessmentRunRequest.new(assessment_run_arn: assessment_run_arn)
        delete_assessment_run(input)
      end
      def delete_assessment_run(input : Types::DeleteAssessmentRunRequest) : Nil
        request = Protocol::JsonRpc.build_request(Model::DELETE_ASSESSMENT_RUN, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        nil
      end

      # Deletes the assessment target that is specified by the ARN of the assessment target.
      def delete_assessment_target(
        assessment_target_arn : String
      ) : Nil
        input = Types::DeleteAssessmentTargetRequest.new(assessment_target_arn: assessment_target_arn)
        delete_assessment_target(input)
      end
      def delete_assessment_target(input : Types::DeleteAssessmentTargetRequest) : Nil
        request = Protocol::JsonRpc.build_request(Model::DELETE_ASSESSMENT_TARGET, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        nil
      end

      # Deletes the assessment template that is specified by the ARN of the assessment template.
      def delete_assessment_template(
        assessment_template_arn : String
      ) : Nil
        input = Types::DeleteAssessmentTemplateRequest.new(assessment_template_arn: assessment_template_arn)
        delete_assessment_template(input)
      end
      def delete_assessment_template(input : Types::DeleteAssessmentTemplateRequest) : Nil
        request = Protocol::JsonRpc.build_request(Model::DELETE_ASSESSMENT_TEMPLATE, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        nil
      end

      # Describes the assessment runs that are specified by the ARNs of the assessment runs.
      def describe_assessment_runs(
        assessment_run_arns : Array(String)
      ) : Types::DescribeAssessmentRunsResponse
        input = Types::DescribeAssessmentRunsRequest.new(assessment_run_arns: assessment_run_arns)
        describe_assessment_runs(input)
      end
      def describe_assessment_runs(input : Types::DescribeAssessmentRunsRequest) : Types::DescribeAssessmentRunsResponse
        request = Protocol::JsonRpc.build_request(Model::DESCRIBE_ASSESSMENT_RUNS, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::DescribeAssessmentRunsResponse, "DescribeAssessmentRuns")
      end

      # Describes the assessment targets that are specified by the ARNs of the assessment targets.
      def describe_assessment_targets(
        assessment_target_arns : Array(String)
      ) : Types::DescribeAssessmentTargetsResponse
        input = Types::DescribeAssessmentTargetsRequest.new(assessment_target_arns: assessment_target_arns)
        describe_assessment_targets(input)
      end
      def describe_assessment_targets(input : Types::DescribeAssessmentTargetsRequest) : Types::DescribeAssessmentTargetsResponse
        request = Protocol::JsonRpc.build_request(Model::DESCRIBE_ASSESSMENT_TARGETS, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::DescribeAssessmentTargetsResponse, "DescribeAssessmentTargets")
      end

      # Describes the assessment templates that are specified by the ARNs of the assessment templates.
      def describe_assessment_templates(
        assessment_template_arns : Array(String)
      ) : Types::DescribeAssessmentTemplatesResponse
        input = Types::DescribeAssessmentTemplatesRequest.new(assessment_template_arns: assessment_template_arns)
        describe_assessment_templates(input)
      end
      def describe_assessment_templates(input : Types::DescribeAssessmentTemplatesRequest) : Types::DescribeAssessmentTemplatesResponse
        request = Protocol::JsonRpc.build_request(Model::DESCRIBE_ASSESSMENT_TEMPLATES, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::DescribeAssessmentTemplatesResponse, "DescribeAssessmentTemplates")
      end

      # Describes the IAM role that enables Amazon Inspector to access your AWS account.
      def describe_cross_account_access_role : Types::DescribeCrossAccountAccessRoleResponse
        request = Protocol::JsonRpc.build_request(Model::DESCRIBE_CROSS_ACCOUNT_ACCESS_ROLE, nil, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::DescribeCrossAccountAccessRoleResponse, "DescribeCrossAccountAccessRole")
      end

      # Describes the exclusions that are specified by the exclusions' ARNs.
      def describe_exclusions(
        exclusion_arns : Array(String),
        locale : String? = nil
      ) : Types::DescribeExclusionsResponse
        input = Types::DescribeExclusionsRequest.new(exclusion_arns: exclusion_arns, locale: locale)
        describe_exclusions(input)
      end
      def describe_exclusions(input : Types::DescribeExclusionsRequest) : Types::DescribeExclusionsResponse
        request = Protocol::JsonRpc.build_request(Model::DESCRIBE_EXCLUSIONS, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::DescribeExclusionsResponse, "DescribeExclusions")
      end

      # Describes the findings that are specified by the ARNs of the findings.
      def describe_findings(
        finding_arns : Array(String),
        locale : String? = nil
      ) : Types::DescribeFindingsResponse
        input = Types::DescribeFindingsRequest.new(finding_arns: finding_arns, locale: locale)
        describe_findings(input)
      end
      def describe_findings(input : Types::DescribeFindingsRequest) : Types::DescribeFindingsResponse
        request = Protocol::JsonRpc.build_request(Model::DESCRIBE_FINDINGS, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::DescribeFindingsResponse, "DescribeFindings")
      end

      # Describes the resource groups that are specified by the ARNs of the resource groups.
      def describe_resource_groups(
        resource_group_arns : Array(String)
      ) : Types::DescribeResourceGroupsResponse
        input = Types::DescribeResourceGroupsRequest.new(resource_group_arns: resource_group_arns)
        describe_resource_groups(input)
      end
      def describe_resource_groups(input : Types::DescribeResourceGroupsRequest) : Types::DescribeResourceGroupsResponse
        request = Protocol::JsonRpc.build_request(Model::DESCRIBE_RESOURCE_GROUPS, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::DescribeResourceGroupsResponse, "DescribeResourceGroups")
      end

      # Describes the rules packages that are specified by the ARNs of the rules packages.
      def describe_rules_packages(
        rules_package_arns : Array(String),
        locale : String? = nil
      ) : Types::DescribeRulesPackagesResponse
        input = Types::DescribeRulesPackagesRequest.new(rules_package_arns: rules_package_arns, locale: locale)
        describe_rules_packages(input)
      end
      def describe_rules_packages(input : Types::DescribeRulesPackagesRequest) : Types::DescribeRulesPackagesResponse
        request = Protocol::JsonRpc.build_request(Model::DESCRIBE_RULES_PACKAGES, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::DescribeRulesPackagesResponse, "DescribeRulesPackages")
      end

      # Produces an assessment report that includes detailed and comprehensive results of a specified
      # assessment run.
      def get_assessment_report(
        assessment_run_arn : String,
        report_file_format : String,
        report_type : String
      ) : Types::GetAssessmentReportResponse
        input = Types::GetAssessmentReportRequest.new(assessment_run_arn: assessment_run_arn, report_file_format: report_file_format, report_type: report_type)
        get_assessment_report(input)
      end
      def get_assessment_report(input : Types::GetAssessmentReportRequest) : Types::GetAssessmentReportResponse
        request = Protocol::JsonRpc.build_request(Model::GET_ASSESSMENT_REPORT, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::GetAssessmentReportResponse, "GetAssessmentReport")
      end

      # Retrieves the exclusions preview (a list of ExclusionPreview objects) specified by the preview
      # token. You can obtain the preview token by running the CreateExclusionsPreview API.
      def get_exclusions_preview(
        assessment_template_arn : String,
        preview_token : String,
        locale : String? = nil,
        max_results : Int32? = nil,
        next_token : String? = nil
      ) : Types::GetExclusionsPreviewResponse
        input = Types::GetExclusionsPreviewRequest.new(assessment_template_arn: assessment_template_arn, preview_token: preview_token, locale: locale, max_results: max_results, next_token: next_token)
        get_exclusions_preview(input)
      end
      def get_exclusions_preview(input : Types::GetExclusionsPreviewRequest) : Types::GetExclusionsPreviewResponse
        request = Protocol::JsonRpc.build_request(Model::GET_EXCLUSIONS_PREVIEW, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::GetExclusionsPreviewResponse, "GetExclusionsPreview")
      end

      # Information about the data that is collected for the specified assessment run.
      def get_telemetry_metadata(
        assessment_run_arn : String
      ) : Types::GetTelemetryMetadataResponse
        input = Types::GetTelemetryMetadataRequest.new(assessment_run_arn: assessment_run_arn)
        get_telemetry_metadata(input)
      end
      def get_telemetry_metadata(input : Types::GetTelemetryMetadataRequest) : Types::GetTelemetryMetadataResponse
        request = Protocol::JsonRpc.build_request(Model::GET_TELEMETRY_METADATA, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::GetTelemetryMetadataResponse, "GetTelemetryMetadata")
      end

      # Lists the agents of the assessment runs that are specified by the ARNs of the assessment runs.
      def list_assessment_run_agents(
        assessment_run_arn : String,
        filter : Types::AgentFilter? = nil,
        max_results : Int32? = nil,
        next_token : String? = nil
      ) : Types::ListAssessmentRunAgentsResponse
        input = Types::ListAssessmentRunAgentsRequest.new(assessment_run_arn: assessment_run_arn, filter: filter, max_results: max_results, next_token: next_token)
        list_assessment_run_agents(input)
      end
      def list_assessment_run_agents(input : Types::ListAssessmentRunAgentsRequest) : Types::ListAssessmentRunAgentsResponse
        request = Protocol::JsonRpc.build_request(Model::LIST_ASSESSMENT_RUN_AGENTS, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::ListAssessmentRunAgentsResponse, "ListAssessmentRunAgents")
      end

      # Lists the assessment runs that correspond to the assessment templates that are specified by the ARNs
      # of the assessment templates.
      def list_assessment_runs(
        assessment_template_arns : Array(String)? = nil,
        filter : Types::AssessmentRunFilter? = nil,
        max_results : Int32? = nil,
        next_token : String? = nil
      ) : Types::ListAssessmentRunsResponse
        input = Types::ListAssessmentRunsRequest.new(assessment_template_arns: assessment_template_arns, filter: filter, max_results: max_results, next_token: next_token)
        list_assessment_runs(input)
      end
      def list_assessment_runs(input : Types::ListAssessmentRunsRequest) : Types::ListAssessmentRunsResponse
        request = Protocol::JsonRpc.build_request(Model::LIST_ASSESSMENT_RUNS, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::ListAssessmentRunsResponse, "ListAssessmentRuns")
      end

      # Lists the ARNs of the assessment targets within this AWS account. For more information about
      # assessment targets, see Amazon Inspector Assessment Targets .
      def list_assessment_targets(
        filter : Types::AssessmentTargetFilter? = nil,
        max_results : Int32? = nil,
        next_token : String? = nil
      ) : Types::ListAssessmentTargetsResponse
        input = Types::ListAssessmentTargetsRequest.new(filter: filter, max_results: max_results, next_token: next_token)
        list_assessment_targets(input)
      end
      def list_assessment_targets(input : Types::ListAssessmentTargetsRequest) : Types::ListAssessmentTargetsResponse
        request = Protocol::JsonRpc.build_request(Model::LIST_ASSESSMENT_TARGETS, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::ListAssessmentTargetsResponse, "ListAssessmentTargets")
      end

      # Lists the assessment templates that correspond to the assessment targets that are specified by the
      # ARNs of the assessment targets.
      def list_assessment_templates(
        assessment_target_arns : Array(String)? = nil,
        filter : Types::AssessmentTemplateFilter? = nil,
        max_results : Int32? = nil,
        next_token : String? = nil
      ) : Types::ListAssessmentTemplatesResponse
        input = Types::ListAssessmentTemplatesRequest.new(assessment_target_arns: assessment_target_arns, filter: filter, max_results: max_results, next_token: next_token)
        list_assessment_templates(input)
      end
      def list_assessment_templates(input : Types::ListAssessmentTemplatesRequest) : Types::ListAssessmentTemplatesResponse
        request = Protocol::JsonRpc.build_request(Model::LIST_ASSESSMENT_TEMPLATES, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::ListAssessmentTemplatesResponse, "ListAssessmentTemplates")
      end

      # Lists all the event subscriptions for the assessment template that is specified by the ARN of the
      # assessment template. For more information, see SubscribeToEvent and UnsubscribeFromEvent .
      def list_event_subscriptions(
        max_results : Int32? = nil,
        next_token : String? = nil,
        resource_arn : String? = nil
      ) : Types::ListEventSubscriptionsResponse
        input = Types::ListEventSubscriptionsRequest.new(max_results: max_results, next_token: next_token, resource_arn: resource_arn)
        list_event_subscriptions(input)
      end
      def list_event_subscriptions(input : Types::ListEventSubscriptionsRequest) : Types::ListEventSubscriptionsResponse
        request = Protocol::JsonRpc.build_request(Model::LIST_EVENT_SUBSCRIPTIONS, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::ListEventSubscriptionsResponse, "ListEventSubscriptions")
      end

      # List exclusions that are generated by the assessment run.
      def list_exclusions(
        assessment_run_arn : String,
        max_results : Int32? = nil,
        next_token : String? = nil
      ) : Types::ListExclusionsResponse
        input = Types::ListExclusionsRequest.new(assessment_run_arn: assessment_run_arn, max_results: max_results, next_token: next_token)
        list_exclusions(input)
      end
      def list_exclusions(input : Types::ListExclusionsRequest) : Types::ListExclusionsResponse
        request = Protocol::JsonRpc.build_request(Model::LIST_EXCLUSIONS, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::ListExclusionsResponse, "ListExclusions")
      end

      # Lists findings that are generated by the assessment runs that are specified by the ARNs of the
      # assessment runs.
      def list_findings(
        assessment_run_arns : Array(String)? = nil,
        filter : Types::FindingFilter? = nil,
        max_results : Int32? = nil,
        next_token : String? = nil
      ) : Types::ListFindingsResponse
        input = Types::ListFindingsRequest.new(assessment_run_arns: assessment_run_arns, filter: filter, max_results: max_results, next_token: next_token)
        list_findings(input)
      end
      def list_findings(input : Types::ListFindingsRequest) : Types::ListFindingsResponse
        request = Protocol::JsonRpc.build_request(Model::LIST_FINDINGS, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::ListFindingsResponse, "ListFindings")
      end

      # Lists all available Amazon Inspector rules packages.
      def list_rules_packages(
        max_results : Int32? = nil,
        next_token : String? = nil
      ) : Types::ListRulesPackagesResponse
        input = Types::ListRulesPackagesRequest.new(max_results: max_results, next_token: next_token)
        list_rules_packages(input)
      end
      def list_rules_packages(input : Types::ListRulesPackagesRequest) : Types::ListRulesPackagesResponse
        request = Protocol::JsonRpc.build_request(Model::LIST_RULES_PACKAGES, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::ListRulesPackagesResponse, "ListRulesPackages")
      end

      # Lists all tags associated with an assessment template.
      def list_tags_for_resource(
        resource_arn : String
      ) : Types::ListTagsForResourceResponse
        input = Types::ListTagsForResourceRequest.new(resource_arn: resource_arn)
        list_tags_for_resource(input)
      end
      def list_tags_for_resource(input : Types::ListTagsForResourceRequest) : Types::ListTagsForResourceResponse
        request = Protocol::JsonRpc.build_request(Model::LIST_TAGS_FOR_RESOURCE, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::ListTagsForResourceResponse, "ListTagsForResource")
      end

      # Previews the agents installed on the EC2 instances that are part of the specified assessment target.
      def preview_agents(
        preview_agents_arn : String,
        max_results : Int32? = nil,
        next_token : String? = nil
      ) : Types::PreviewAgentsResponse
        input = Types::PreviewAgentsRequest.new(preview_agents_arn: preview_agents_arn, max_results: max_results, next_token: next_token)
        preview_agents(input)
      end
      def preview_agents(input : Types::PreviewAgentsRequest) : Types::PreviewAgentsResponse
        request = Protocol::JsonRpc.build_request(Model::PREVIEW_AGENTS, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::PreviewAgentsResponse, "PreviewAgents")
      end

      # Registers the IAM role that grants Amazon Inspector access to AWS Services needed to perform
      # security assessments.
      def register_cross_account_access_role(
        role_arn : String
      ) : Nil
        input = Types::RegisterCrossAccountAccessRoleRequest.new(role_arn: role_arn)
        register_cross_account_access_role(input)
      end
      def register_cross_account_access_role(input : Types::RegisterCrossAccountAccessRoleRequest) : Nil
        request = Protocol::JsonRpc.build_request(Model::REGISTER_CROSS_ACCOUNT_ACCESS_ROLE, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        nil
      end

      # Removes entire attributes (key and value pairs) from the findings that are specified by the ARNs of
      # the findings where an attribute with the specified key exists.
      def remove_attributes_from_findings(
        attribute_keys : Array(String),
        finding_arns : Array(String)
      ) : Types::RemoveAttributesFromFindingsResponse
        input = Types::RemoveAttributesFromFindingsRequest.new(attribute_keys: attribute_keys, finding_arns: finding_arns)
        remove_attributes_from_findings(input)
      end
      def remove_attributes_from_findings(input : Types::RemoveAttributesFromFindingsRequest) : Types::RemoveAttributesFromFindingsResponse
        request = Protocol::JsonRpc.build_request(Model::REMOVE_ATTRIBUTES_FROM_FINDINGS, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::RemoveAttributesFromFindingsResponse, "RemoveAttributesFromFindings")
      end

      # Sets tags (key and value pairs) to the assessment template that is specified by the ARN of the
      # assessment template.
      def set_tags_for_resource(
        resource_arn : String,
        tags : Array(Types::Tag)? = nil
      ) : Nil
        input = Types::SetTagsForResourceRequest.new(resource_arn: resource_arn, tags: tags)
        set_tags_for_resource(input)
      end
      def set_tags_for_resource(input : Types::SetTagsForResourceRequest) : Nil
        request = Protocol::JsonRpc.build_request(Model::SET_TAGS_FOR_RESOURCE, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        nil
      end

      # Starts the assessment run specified by the ARN of the assessment template. For this API to function
      # properly, you must not exceed the limit of running up to 500 concurrent agents per AWS account.
      def start_assessment_run(
        assessment_template_arn : String,
        assessment_run_name : String? = nil
      ) : Types::StartAssessmentRunResponse
        input = Types::StartAssessmentRunRequest.new(assessment_template_arn: assessment_template_arn, assessment_run_name: assessment_run_name)
        start_assessment_run(input)
      end
      def start_assessment_run(input : Types::StartAssessmentRunRequest) : Types::StartAssessmentRunResponse
        request = Protocol::JsonRpc.build_request(Model::START_ASSESSMENT_RUN, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        Protocol::JsonRpc.parse_response(response, Types::StartAssessmentRunResponse, "StartAssessmentRun")
      end

      # Stops the assessment run that is specified by the ARN of the assessment run.
      def stop_assessment_run(
        assessment_run_arn : String,
        stop_action : String? = nil
      ) : Nil
        input = Types::StopAssessmentRunRequest.new(assessment_run_arn: assessment_run_arn, stop_action: stop_action)
        stop_assessment_run(input)
      end
      def stop_assessment_run(input : Types::StopAssessmentRunRequest) : Nil
        request = Protocol::JsonRpc.build_request(Model::STOP_ASSESSMENT_RUN, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        nil
      end

      # Enables the process of sending Amazon Simple Notification Service (SNS) notifications about a
      # specified event to a specified SNS topic.
      def subscribe_to_event(
        event : String,
        resource_arn : String,
        topic_arn : String
      ) : Nil
        input = Types::SubscribeToEventRequest.new(event: event, resource_arn: resource_arn, topic_arn: topic_arn)
        subscribe_to_event(input)
      end
      def subscribe_to_event(input : Types::SubscribeToEventRequest) : Nil
        request = Protocol::JsonRpc.build_request(Model::SUBSCRIBE_TO_EVENT, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        nil
      end

      # Disables the process of sending Amazon Simple Notification Service (SNS) notifications about a
      # specified event to a specified SNS topic.
      def unsubscribe_from_event(
        event : String,
        resource_arn : String,
        topic_arn : String
      ) : Nil
        input = Types::UnsubscribeFromEventRequest.new(event: event, resource_arn: resource_arn, topic_arn: topic_arn)
        unsubscribe_from_event(input)
      end
      def unsubscribe_from_event(input : Types::UnsubscribeFromEventRequest) : Nil
        request = Protocol::JsonRpc.build_request(Model::UNSUBSCRIBE_FROM_EVENT, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        nil
      end

      # Updates the assessment target that is specified by the ARN of the assessment target. If
      # resourceGroupArn is not specified, all EC2 instances in the current AWS account and region are
      # included in the assessment target.
      def update_assessment_target(
        assessment_target_arn : String,
        assessment_target_name : String,
        resource_group_arn : String? = nil
      ) : Nil
        input = Types::UpdateAssessmentTargetRequest.new(assessment_target_arn: assessment_target_arn, assessment_target_name: assessment_target_name, resource_group_arn: resource_group_arn)
        update_assessment_target(input)
      end
      def update_assessment_target(input : Types::UpdateAssessmentTargetRequest) : Nil
        request = Protocol::JsonRpc.build_request(Model::UPDATE_ASSESSMENT_TARGET, input, endpoint)
        request = request.with_headers(endpoint_headers)
        response = runtime.execute(request)
        raise Protocol::JsonRpc.parse_error(response) if response.status >= 300
        nil
      end
    end
  end
end
