require "json"
require "time"

module AwsSdk
  module NotificationsContacts
    module Types

      # You do not have sufficient access to perform this action.
      struct AccessDeniedException
        include JSON::Serializable

        @[JSON::Field(key: "message")]
        getter message : String

        def initialize(
          @message : String
        )
        end
      end

      struct ActivateEmailContactRequest
        include JSON::Serializable

        # The Amazon Resource Name (ARN) of the resource.
        @[JSON::Field(key: "arn")]
        getter arn : String

        # The activation code for this email contact. An email contact has a maximum of five activation
        # attempts. Activation codes expire after 12 hours and are generated by the SendActivationCode API
        # action.
        @[JSON::Field(key: "code")]
        getter code : String

        def initialize(
          @arn : String,
          @code : String
        )
        end
      end

      struct ActivateEmailContactResponse
        include JSON::Serializable

        def initialize
        end
      end

      # Updating or deleting a resource can cause an inconsistent state.
      struct ConflictException
        include JSON::Serializable

        @[JSON::Field(key: "message")]
        getter message : String

        # The resource ID that prompted the conflict error.
        @[JSON::Field(key: "resourceId")]
        getter resource_id : String

        # The resource type that prompted the conflict error.
        @[JSON::Field(key: "resourceType")]
        getter resource_type : String

        def initialize(
          @message : String,
          @resource_id : String,
          @resource_type : String
        )
        end
      end

      struct CreateEmailContactRequest
        include JSON::Serializable

        # The email address this email contact points to. The activation email and any subscribed emails are
        # sent here. This email address can't receive emails until it's activated.
        @[JSON::Field(key: "emailAddress")]
        getter email_address : String

        # The name of the email contact.
        @[JSON::Field(key: "name")]
        getter name : String

        # A map of tags assigned to a resource. A tag is a string-to-string map of key-value pairs.
        @[JSON::Field(key: "tags")]
        getter tags : Hash(String, String)?

        def initialize(
          @email_address : String,
          @name : String,
          @tags : Hash(String, String)? = nil
        )
        end
      end

      struct CreateEmailContactResponse
        include JSON::Serializable

        # The Amazon Resource Name (ARN) of the resource.
        @[JSON::Field(key: "arn")]
        getter arn : String

        def initialize(
          @arn : String
        )
        end
      end

      struct DeleteEmailContactRequest
        include JSON::Serializable

        # The Amazon Resource Name (ARN) of the resource.
        @[JSON::Field(key: "arn")]
        getter arn : String

        def initialize(
          @arn : String
        )
        end
      end

      struct DeleteEmailContactResponse
        include JSON::Serializable

        def initialize
        end
      end

      # An email contact.
      struct EmailContact
        include JSON::Serializable

        # The email address this email contact points to. The activation email and any subscribed emails are
        # sent here.
        @[JSON::Field(key: "address")]
        getter address : String

        # The Amazon Resource Name (ARN) of the email contact.
        @[JSON::Field(key: "arn")]
        getter arn : String

        # The creation time of the resource.
        @[JSON::Field(key: "creationTime")]
        getter creation_time : Time

        # The name of the email contact.
        @[JSON::Field(key: "name")]
        getter name : String

        # The status of the email contact. Only activated email contacts receive emails.
        @[JSON::Field(key: "status")]
        getter status : String

        # The time the resource was last updated.
        @[JSON::Field(key: "updateTime")]
        getter update_time : Time

        def initialize(
          @address : String,
          @arn : String,
          @creation_time : Time,
          @name : String,
          @status : String,
          @update_time : Time
        )
        end
      end

      struct GetEmailContactRequest
        include JSON::Serializable

        # The Amazon Resource Name (ARN) of the email contact to get.
        @[JSON::Field(key: "arn")]
        getter arn : String

        def initialize(
          @arn : String
        )
        end
      end

      struct GetEmailContactResponse
        include JSON::Serializable

        # The email contact for the provided email address.
        @[JSON::Field(key: "emailContact")]
        getter email_contact : Types::EmailContact

        def initialize(
          @email_contact : Types::EmailContact
        )
        end
      end

      # Unexpected error during processing of request.
      struct InternalServerException
        include JSON::Serializable

        @[JSON::Field(key: "message")]
        getter message : String

        def initialize(
          @message : String
        )
        end
      end

      struct ListEmailContactsRequest
        include JSON::Serializable

        # The maximum number of results to include in the response. If more results exist than the specified
        # MaxResults value, a token is included in the response so that the remaining results can be
        # retrieved.
        @[JSON::Field(key: "maxResults")]
        getter max_results : Int32?

        # An optional token returned from a prior request. Use this token for pagination of results from this
        # action. If this parameter is specified, the response includes only results beyond the token, up to
        # the value specified by MaxResults.
        @[JSON::Field(key: "nextToken")]
        getter next_token : String?

        def initialize(
          @max_results : Int32? = nil,
          @next_token : String? = nil
        )
        end
      end

      struct ListEmailContactsResponse
        include JSON::Serializable

        # A list of email contacts.
        @[JSON::Field(key: "emailContacts")]
        getter email_contacts : Array(Types::EmailContact)

        # An optional token returned from a prior request. Use this token for pagination of results from this
        # action. If this parameter is specified, the response includes only results beyond the token, up to
        # the value specified by MaxResults.
        @[JSON::Field(key: "nextToken")]
        getter next_token : String?

        def initialize(
          @email_contacts : Array(Types::EmailContact),
          @next_token : String? = nil
        )
        end
      end

      struct ListTagsForResourceRequest
        include JSON::Serializable

        # The ARN you specified to list the tags of.
        @[JSON::Field(key: "arn")]
        getter arn : String

        def initialize(
          @arn : String
        )
        end
      end

      struct ListTagsForResourceResponse
        include JSON::Serializable

        # Key-value pairs that are assigned to a resource, usually for the purpose of grouping and searching
        # for items. Tags are metadata that you define.
        @[JSON::Field(key: "tags")]
        getter tags : Hash(String, String)?

        def initialize(
          @tags : Hash(String, String)? = nil
        )
        end
      end

      # Your request references a resource which does not exist.
      struct ResourceNotFoundException
        include JSON::Serializable

        @[JSON::Field(key: "message")]
        getter message : String

        # The ID of the resource that wasn't found.
        @[JSON::Field(key: "resourceId")]
        getter resource_id : String

        # The type of resource that wasn't found.
        @[JSON::Field(key: "resourceType")]
        getter resource_type : String

        def initialize(
          @message : String,
          @resource_id : String,
          @resource_type : String
        )
        end
      end

      struct SendActivationCodeRequest
        include JSON::Serializable

        # The Amazon Resource Name (ARN) of the resource.
        @[JSON::Field(key: "arn")]
        getter arn : String

        def initialize(
          @arn : String
        )
        end
      end

      struct SendActivationCodeResponse
        include JSON::Serializable

        def initialize
        end
      end

      # Request would cause a service quota to be exceeded.
      struct ServiceQuotaExceededException
        include JSON::Serializable

        @[JSON::Field(key: "message")]
        getter message : String

        # The code for the service quota in Service Quotas .
        @[JSON::Field(key: "quotaCode")]
        getter quota_code : String

        # The ID of the resource that exceeds the service quota.
        @[JSON::Field(key: "resourceId")]
        getter resource_id : String

        # The type of the resource that exceeds the service quota.
        @[JSON::Field(key: "resourceType")]
        getter resource_type : String

        # The code for the service quota exceeded in Service Quotas .
        @[JSON::Field(key: "serviceCode")]
        getter service_code : String

        def initialize(
          @message : String,
          @quota_code : String,
          @resource_id : String,
          @resource_type : String,
          @service_code : String
        )
        end
      end

      struct TagResourceRequest
        include JSON::Serializable

        # The ARN of the configuration.
        @[JSON::Field(key: "arn")]
        getter arn : String

        # A list of tags to apply to the configuration.
        @[JSON::Field(key: "tags")]
        getter tags : Hash(String, String)

        def initialize(
          @arn : String,
          @tags : Hash(String, String)
        )
        end
      end

      struct TagResourceResponse
        include JSON::Serializable

        def initialize
        end
      end

      # The request was denied due to request throttling.
      struct ThrottlingException
        include JSON::Serializable

        @[JSON::Field(key: "message")]
        getter message : String

        # Identifies the quota that is being throttled.
        @[JSON::Field(key: "quotaCode")]
        getter quota_code : String?

        # The number of seconds a client should wait before retrying the request.
        @[JSON::Field(key: "Retry-After")]
        getter retry_after_seconds : Int32?

        # Identifies the service being throttled.
        @[JSON::Field(key: "serviceCode")]
        getter service_code : String?

        def initialize(
          @message : String,
          @quota_code : String? = nil,
          @retry_after_seconds : Int32? = nil,
          @service_code : String? = nil
        )
        end
      end

      struct UntagResourceRequest
        include JSON::Serializable

        # The value of the resource that will have the tag removed. An Amazon Resource Name (ARN) is an
        # identifier for a specific AWS resource, such as a server, user, or role.
        @[JSON::Field(key: "arn")]
        getter arn : String

        # Specifies a list of tag keys that you want to remove from the specified resources.
        @[JSON::Field(key: "tagKeys")]
        getter tag_keys : Array(String)

        def initialize(
          @arn : String,
          @tag_keys : Array(String)
        )
        end
      end

      struct UntagResourceResponse
        include JSON::Serializable

        def initialize
        end
      end

      # The input fails to satisfy the constraints specified by an AWS service.
      struct ValidationException
        include JSON::Serializable

        @[JSON::Field(key: "message")]
        getter message : String

        # The reason why your input is considered invalid.
        @[JSON::Field(key: "reason")]
        getter reason : String

        # The list of input fields that are invalid.
        @[JSON::Field(key: "fieldList")]
        getter field_list : Array(Types::ValidationExceptionField)?

        def initialize(
          @message : String,
          @reason : String,
          @field_list : Array(Types::ValidationExceptionField)? = nil
        )
        end
      end

      # Stores information about a field passed inside a request that resulted in an exception.
      struct ValidationExceptionField
        include JSON::Serializable

        # A message with the reason for the validation exception error.
        @[JSON::Field(key: "message")]
        getter message : String

        # The field name where the invalid entry was detected.
        @[JSON::Field(key: "name")]
        getter name : String

        def initialize(
          @message : String,
          @name : String
        )
        end
      end
    end
  end
end
