module Aws
  module CodeGuruSecurity
    class Client
      getter endpoint : String
      getter endpoint_headers : Hash(String, String)
      getter region : String

      def initialize(
        endpoint : String? = nil,
        region : String? = nil,
        profile : String? = nil,
        use_fips : Bool? = nil,
        use_dualstack : Bool? = nil
      )
        @region = region || Aws::Runtime::Defaults.resolve_region(profile)
        endpoint_provider = Aws::Runtime::EndpointProvider.new(Model::ENDPOINT_PREFIX, Model::ENDPOINT_RULE_SET_JSON)
        endpoint_result = endpoint_provider.resolve(@region, endpoint, use_fips, use_dualstack)
        @endpoint = endpoint_result.url
        @endpoint_headers = endpoint_result.headers
      end

      # Returns a list of requested findings from standard scans.

      def batch_get_findings(
        finding_identifiers : Array(Types::FindingIdentifier)
      ) : Protocol::Request
        input = Types::BatchGetFindingsRequest.new(finding_identifiers: finding_identifiers)
        batch_get_findings(input)
      end

      def batch_get_findings(input : Types::BatchGetFindingsRequest) : Protocol::Request
        request = Protocol::RestJson.build_request(Model::BATCH_GET_FINDINGS, input, endpoint)
        Protocol::Request.new(request.method, request.uri, request.headers.merge(endpoint_headers), request.body)
      end

      # Use to create a scan using code uploaded to an Amazon S3 bucket.

      def create_scan(
        resource_id : Types::ResourceId,
        scan_name : String,
        analysis_type : String? = nil,
        client_token : String? = nil,
        scan_type : String? = nil,
        tags : Hash(String, String)? = nil
      ) : Protocol::Request
        input = Types::CreateScanRequest.new(resource_id: resource_id, scan_name: scan_name, analysis_type: analysis_type, client_token: client_token, scan_type: scan_type, tags: tags)
        create_scan(input)
      end

      def create_scan(input : Types::CreateScanRequest) : Protocol::Request
        request = Protocol::RestJson.build_request(Model::CREATE_SCAN, input, endpoint)
        Protocol::Request.new(request.method, request.uri, request.headers.merge(endpoint_headers), request.body)
      end

      # Generates a pre-signed URL, request headers used to upload a code resource, and code artifact
      # identifier for the uploaded resource. You can upload your code resource to the URL with the request
      # headers using any HTTP client.

      def create_upload_url(
        scan_name : String
      ) : Protocol::Request
        input = Types::CreateUploadUrlRequest.new(scan_name: scan_name)
        create_upload_url(input)
      end

      def create_upload_url(input : Types::CreateUploadUrlRequest) : Protocol::Request
        request = Protocol::RestJson.build_request(Model::CREATE_UPLOAD_URL, input, endpoint)
        Protocol::Request.new(request.method, request.uri, request.headers.merge(endpoint_headers), request.body)
      end

      # Use to get the encryption configuration for an account.

      def get_account_configuration : Protocol::Request
        input = Types::GetAccountConfigurationRequest.new
        get_account_configuration(input)
      end

      def get_account_configuration(input : Types::GetAccountConfigurationRequest) : Protocol::Request
        request = Protocol::RestJson.build_request(Model::GET_ACCOUNT_CONFIGURATION, input, endpoint)
        Protocol::Request.new(request.method, request.uri, request.headers.merge(endpoint_headers), request.body)
      end

      # Returns a list of all findings generated by a particular scan.

      def get_findings(
        scan_name : String,
        max_results : Int32? = nil,
        next_token : String? = nil,
        status : String? = nil
      ) : Protocol::Request
        input = Types::GetFindingsRequest.new(scan_name: scan_name, max_results: max_results, next_token: next_token, status: status)
        get_findings(input)
      end

      def get_findings(input : Types::GetFindingsRequest) : Protocol::Request
        request = Protocol::RestJson.build_request(Model::GET_FINDINGS, input, endpoint)
        Protocol::Request.new(request.method, request.uri, request.headers.merge(endpoint_headers), request.body)
      end

      # Returns a summary of metrics for an account from a specified date, including number of open
      # findings, the categories with most findings, the scans with most open findings, and scans with most
      # open critical findings.

      def get_metrics_summary(
        date : Time
      ) : Protocol::Request
        input = Types::GetMetricsSummaryRequest.new(date: date)
        get_metrics_summary(input)
      end

      def get_metrics_summary(input : Types::GetMetricsSummaryRequest) : Protocol::Request
        request = Protocol::RestJson.build_request(Model::GET_METRICS_SUMMARY, input, endpoint)
        Protocol::Request.new(request.method, request.uri, request.headers.merge(endpoint_headers), request.body)
      end

      # Returns details about a scan, including whether or not a scan has completed.

      def get_scan(
        scan_name : String,
        run_id : String? = nil
      ) : Protocol::Request
        input = Types::GetScanRequest.new(scan_name: scan_name, run_id: run_id)
        get_scan(input)
      end

      def get_scan(input : Types::GetScanRequest) : Protocol::Request
        request = Protocol::RestJson.build_request(Model::GET_SCAN, input, endpoint)
        Protocol::Request.new(request.method, request.uri, request.headers.merge(endpoint_headers), request.body)
      end

      # Returns metrics about all findings in an account within a specified time range.

      def list_findings_metrics(
        end_date : Time,
        start_date : Time,
        max_results : Int32? = nil,
        next_token : String? = nil
      ) : Protocol::Request
        input = Types::ListFindingsMetricsRequest.new(end_date: end_date, start_date: start_date, max_results: max_results, next_token: next_token)
        list_findings_metrics(input)
      end

      def list_findings_metrics(input : Types::ListFindingsMetricsRequest) : Protocol::Request
        request = Protocol::RestJson.build_request(Model::LIST_FINDINGS_METRICS, input, endpoint)
        Protocol::Request.new(request.method, request.uri, request.headers.merge(endpoint_headers), request.body)
      end

      # Returns a list of all scans in an account. Does not return EXPRESS scans.

      def list_scans(
        max_results : Int32? = nil,
        next_token : String? = nil
      ) : Protocol::Request
        input = Types::ListScansRequest.new(max_results: max_results, next_token: next_token)
        list_scans(input)
      end

      def list_scans(input : Types::ListScansRequest) : Protocol::Request
        request = Protocol::RestJson.build_request(Model::LIST_SCANS, input, endpoint)
        Protocol::Request.new(request.method, request.uri, request.headers.merge(endpoint_headers), request.body)
      end

      # Returns a list of all tags associated with a scan.

      def list_tags_for_resource(
        resource_arn : String
      ) : Protocol::Request
        input = Types::ListTagsForResourceRequest.new(resource_arn: resource_arn)
        list_tags_for_resource(input)
      end

      def list_tags_for_resource(input : Types::ListTagsForResourceRequest) : Protocol::Request
        request = Protocol::RestJson.build_request(Model::LIST_TAGS_FOR_RESOURCE, input, endpoint)
        Protocol::Request.new(request.method, request.uri, request.headers.merge(endpoint_headers), request.body)
      end

      # Use to add one or more tags to an existing scan.

      def tag_resource(
        resource_arn : String,
        tags : Hash(String, String)
      ) : Protocol::Request
        input = Types::TagResourceRequest.new(resource_arn: resource_arn, tags: tags)
        tag_resource(input)
      end

      def tag_resource(input : Types::TagResourceRequest) : Protocol::Request
        request = Protocol::RestJson.build_request(Model::TAG_RESOURCE, input, endpoint)
        Protocol::Request.new(request.method, request.uri, request.headers.merge(endpoint_headers), request.body)
      end

      # Use to remove one or more tags from an existing scan.

      def untag_resource(
        resource_arn : String,
        tag_keys : Array(String)
      ) : Protocol::Request
        input = Types::UntagResourceRequest.new(resource_arn: resource_arn, tag_keys: tag_keys)
        untag_resource(input)
      end

      def untag_resource(input : Types::UntagResourceRequest) : Protocol::Request
        request = Protocol::RestJson.build_request(Model::UNTAG_RESOURCE, input, endpoint)
        Protocol::Request.new(request.method, request.uri, request.headers.merge(endpoint_headers), request.body)
      end

      # Use to update the encryption configuration for an account.

      def update_account_configuration(
        encryption_config : Types::EncryptionConfig
      ) : Protocol::Request
        input = Types::UpdateAccountConfigurationRequest.new(encryption_config: encryption_config)
        update_account_configuration(input)
      end

      def update_account_configuration(input : Types::UpdateAccountConfigurationRequest) : Protocol::Request
        request = Protocol::RestJson.build_request(Model::UPDATE_ACCOUNT_CONFIGURATION, input, endpoint)
        Protocol::Request.new(request.method, request.uri, request.headers.merge(endpoint_headers), request.body)
      end
    end
  end
end
