require "json"

module AwsSdk
  module SSOOIDC
    module Types

      # You do not have sufficient access to perform this action.
      struct AccessDeniedException
        include JSON::Serializable

        # Single error code. For this exception the value will be access_denied .
        @[JSON::Field(key: "error")]
        getter error : String?

        # Human-readable text providing additional information, used to assist the client developer in
        # understanding the error that occurred.
        @[JSON::Field(key: "error_description")]
        getter error_description : String?

        # A string that uniquely identifies a reason for the error.
        @[JSON::Field(key: "reason")]
        getter reason : String?

        def initialize(
          @error : String? = nil,
          @error_description : String? = nil,
          @reason : String? = nil
        )
        end
      end

      # Indicates that a request to authorize a client with an access user session token is pending.
      struct AuthorizationPendingException
        include JSON::Serializable

        # Single error code. For this exception the value will be authorization_pending .
        @[JSON::Field(key: "error")]
        getter error : String?

        # Human-readable text providing additional information, used to assist the client developer in
        # understanding the error that occurred.
        @[JSON::Field(key: "error_description")]
        getter error_description : String?

        def initialize(
          @error : String? = nil,
          @error_description : String? = nil
        )
        end
      end

      # This structure contains Amazon Web Services-specific parameter extensions and the identity context .
      struct AwsAdditionalDetails
        include JSON::Serializable

        # The trusted context assertion is signed and encrypted by STS. It provides access to
        # sts:identity_context claim in the idToken without JWT parsing Identity context comprises information
        # that Amazon Web Services services use to make authorization decisions when they receive requests.
        @[JSON::Field(key: "identityContext")]
        getter identity_context : String?

        def initialize(
          @identity_context : String? = nil
        )
        end
      end

      struct CreateTokenRequest
        include JSON::Serializable

        # The unique identifier string for the client or application. This value comes from the result of the
        # RegisterClient API.
        @[JSON::Field(key: "clientId")]
        getter client_id : String

        # A secret string generated for the client. This value should come from the persisted result of the
        # RegisterClient API.
        @[JSON::Field(key: "clientSecret")]
        getter client_secret : String

        # Supports the following OAuth grant types: Authorization Code, Device Code, and Refresh Token.
        # Specify one of the following values, depending on the grant type that you want: * Authorization Code
        # - authorization_code * Device Code - urn:ietf:params:oauth:grant-type:device_code * Refresh Token -
        # refresh_token
        @[JSON::Field(key: "grantType")]
        getter grant_type : String

        # Used only when calling this API for the Authorization Code grant type. The short-lived code is used
        # to identify this authorization request.
        @[JSON::Field(key: "code")]
        getter code : String?

        # Used only when calling this API for the Authorization Code grant type. This value is generated by
        # the client and presented to validate the original code challenge value the client passed at
        # authorization time.
        @[JSON::Field(key: "codeVerifier")]
        getter code_verifier : String?

        # Used only when calling this API for the Device Code grant type. This short-lived code is used to
        # identify this authorization request. This comes from the result of the StartDeviceAuthorization API.
        @[JSON::Field(key: "deviceCode")]
        getter device_code : String?

        # Used only when calling this API for the Authorization Code grant type. This value specifies the
        # location of the client or application that has registered to receive the authorization code.
        @[JSON::Field(key: "redirectUri")]
        getter redirect_uri : String?

        # Used only when calling this API for the Refresh Token grant type. This token is used to refresh
        # short-lived tokens, such as the access token, that might expire. For more information about the
        # features and limitations of the current IAM Identity Center OIDC implementation, see Considerations
        # for Using this Guide in the IAM Identity Center OIDC API Reference .
        @[JSON::Field(key: "refreshToken")]
        getter refresh_token : String?

        # The list of scopes for which authorization is requested. This parameter has no effect; the access
        # token will always include all scopes configured during client registration.
        @[JSON::Field(key: "scope")]
        getter scope : Array(String)?

        def initialize(
          @client_id : String,
          @client_secret : String,
          @grant_type : String,
          @code : String? = nil,
          @code_verifier : String? = nil,
          @device_code : String? = nil,
          @redirect_uri : String? = nil,
          @refresh_token : String? = nil,
          @scope : Array(String)? = nil
        )
        end
      end

      struct CreateTokenResponse
        include JSON::Serializable

        # A bearer token to access Amazon Web Services accounts and applications assigned to a user.
        @[JSON::Field(key: "accessToken")]
        getter access_token : String?

        # Indicates the time in seconds when an access token will expire.
        @[JSON::Field(key: "expiresIn")]
        getter expires_in : Int32?

        # The idToken is not implemented or supported. For more information about the features and limitations
        # of the current IAM Identity Center OIDC implementation, see Considerations for Using this Guide in
        # the IAM Identity Center OIDC API Reference . A JSON Web Token (JWT) that identifies who is
        # associated with the issued access token.
        @[JSON::Field(key: "idToken")]
        getter id_token : String?

        # A token that, if present, can be used to refresh a previously issued access token that might have
        # expired. For more information about the features and limitations of the current IAM Identity Center
        # OIDC implementation, see Considerations for Using this Guide in the IAM Identity Center OIDC API
        # Reference .
        @[JSON::Field(key: "refreshToken")]
        getter refresh_token : String?

        # Used to notify the client that the returned token is an access token. The supported token type is
        # Bearer .
        @[JSON::Field(key: "tokenType")]
        getter token_type : String?

        def initialize(
          @access_token : String? = nil,
          @expires_in : Int32? = nil,
          @id_token : String? = nil,
          @refresh_token : String? = nil,
          @token_type : String? = nil
        )
        end
      end

      struct CreateTokenWithIAMRequest
        include JSON::Serializable

        # The unique identifier string for the client or application. This value is an application ARN that
        # has OAuth grants configured.
        @[JSON::Field(key: "clientId")]
        getter client_id : String

        # Supports the following OAuth grant types: Authorization Code, Refresh Token, JWT Bearer, and Token
        # Exchange. Specify one of the following values, depending on the grant type that you want: *
        # Authorization Code - authorization_code * Refresh Token - refresh_token * JWT Bearer -
        # urn:ietf:params:oauth:grant-type:jwt-bearer * Token Exchange -
        # urn:ietf:params:oauth:grant-type:token-exchange
        @[JSON::Field(key: "grantType")]
        getter grant_type : String

        # Used only when calling this API for the JWT Bearer grant type. This value specifies the JSON Web
        # Token (JWT) issued by a trusted token issuer. To authorize a trusted token issuer, configure the JWT
        # Bearer GrantOptions for the application.
        @[JSON::Field(key: "assertion")]
        getter assertion : String?

        # Used only when calling this API for the Authorization Code grant type. This short-lived code is used
        # to identify this authorization request. The code is obtained through a redirect from IAM Identity
        # Center to a redirect URI persisted in the Authorization Code GrantOptions for the application.
        @[JSON::Field(key: "code")]
        getter code : String?

        # Used only when calling this API for the Authorization Code grant type. This value is generated by
        # the client and presented to validate the original code challenge value the client passed at
        # authorization time.
        @[JSON::Field(key: "codeVerifier")]
        getter code_verifier : String?

        # Used only when calling this API for the Authorization Code grant type. This value specifies the
        # location of the client or application that has registered to receive the authorization code.
        @[JSON::Field(key: "redirectUri")]
        getter redirect_uri : String?

        # Used only when calling this API for the Refresh Token grant type. This token is used to refresh
        # short-lived tokens, such as the access token, that might expire. For more information about the
        # features and limitations of the current IAM Identity Center OIDC implementation, see Considerations
        # for Using this Guide in the IAM Identity Center OIDC API Reference .
        @[JSON::Field(key: "refreshToken")]
        getter refresh_token : String?

        # Used only when calling this API for the Token Exchange grant type. This value specifies the type of
        # token that the requester can receive. The following values are supported: * Access Token -
        # urn:ietf:params:oauth:token-type:access_token * Refresh Token -
        # urn:ietf:params:oauth:token-type:refresh_token
        @[JSON::Field(key: "requestedTokenType")]
        getter requested_token_type : String?

        # The list of scopes for which authorization is requested. The access token that is issued is limited
        # to the scopes that are granted. If the value is not specified, IAM Identity Center authorizes all
        # scopes configured for the application, including the following default scopes: openid , aws ,
        # sts:identity_context .
        @[JSON::Field(key: "scope")]
        getter scope : Array(String)?

        # Used only when calling this API for the Token Exchange grant type. This value specifies the subject
        # of the exchange. The value of the subject token must be an access token issued by IAM Identity
        # Center to a different client or application. The access token must have authorized scopes that
        # indicate the requested application as a target audience.
        @[JSON::Field(key: "subjectToken")]
        getter subject_token : String?

        # Used only when calling this API for the Token Exchange grant type. This value specifies the type of
        # token that is passed as the subject of the exchange. The following value is supported: * Access
        # Token - urn:ietf:params:oauth:token-type:access_token
        @[JSON::Field(key: "subjectTokenType")]
        getter subject_token_type : String?

        def initialize(
          @client_id : String,
          @grant_type : String,
          @assertion : String? = nil,
          @code : String? = nil,
          @code_verifier : String? = nil,
          @redirect_uri : String? = nil,
          @refresh_token : String? = nil,
          @requested_token_type : String? = nil,
          @scope : Array(String)? = nil,
          @subject_token : String? = nil,
          @subject_token_type : String? = nil
        )
        end
      end

      struct CreateTokenWithIAMResponse
        include JSON::Serializable

        # A bearer token to access Amazon Web Services accounts and applications assigned to a user.
        @[JSON::Field(key: "accessToken")]
        getter access_token : String?

        # A structure containing information from IAM Identity Center managed user and group information.
        @[JSON::Field(key: "awsAdditionalDetails")]
        getter aws_additional_details : Types::AwsAdditionalDetails?

        # Indicates the time in seconds when an access token will expire.
        @[JSON::Field(key: "expiresIn")]
        getter expires_in : Int32?

        # A JSON Web Token (JWT) that identifies the user associated with the issued access token.
        @[JSON::Field(key: "idToken")]
        getter id_token : String?

        # Indicates the type of tokens that are issued by IAM Identity Center. The following values are
        # supported: * Access Token - urn:ietf:params:oauth:token-type:access_token * Refresh Token -
        # urn:ietf:params:oauth:token-type:refresh_token
        @[JSON::Field(key: "issuedTokenType")]
        getter issued_token_type : String?

        # A token that, if present, can be used to refresh a previously issued access token that might have
        # expired. For more information about the features and limitations of the current IAM Identity Center
        # OIDC implementation, see Considerations for Using this Guide in the IAM Identity Center OIDC API
        # Reference .
        @[JSON::Field(key: "refreshToken")]
        getter refresh_token : String?

        # The list of scopes for which authorization is granted. The access token that is issued is limited to
        # the scopes that are granted.
        @[JSON::Field(key: "scope")]
        getter scope : Array(String)?

        # Used to notify the requester that the returned token is an access token. The supported token type is
        # Bearer .
        @[JSON::Field(key: "tokenType")]
        getter token_type : String?

        def initialize(
          @access_token : String? = nil,
          @aws_additional_details : Types::AwsAdditionalDetails? = nil,
          @expires_in : Int32? = nil,
          @id_token : String? = nil,
          @issued_token_type : String? = nil,
          @refresh_token : String? = nil,
          @scope : Array(String)? = nil,
          @token_type : String? = nil
        )
        end
      end

      # Indicates that the token issued by the service is expired and is no longer valid.
      struct ExpiredTokenException
        include JSON::Serializable

        # Single error code. For this exception the value will be expired_token .
        @[JSON::Field(key: "error")]
        getter error : String?

        # Human-readable text providing additional information, used to assist the client developer in
        # understanding the error that occurred.
        @[JSON::Field(key: "error_description")]
        getter error_description : String?

        def initialize(
          @error : String? = nil,
          @error_description : String? = nil
        )
        end
      end

      # Indicates that an error from the service occurred while trying to process a request.
      struct InternalServerException
        include JSON::Serializable

        # Single error code. For this exception the value will be server_error .
        @[JSON::Field(key: "error")]
        getter error : String?

        # Human-readable text providing additional information, used to assist the client developer in
        # understanding the error that occurred.
        @[JSON::Field(key: "error_description")]
        getter error_description : String?

        def initialize(
          @error : String? = nil,
          @error_description : String? = nil
        )
        end
      end

      # Indicates that the clientId or clientSecret in the request is invalid. For example, this can occur
      # when a client sends an incorrect clientId or an expired clientSecret .
      struct InvalidClientException
        include JSON::Serializable

        # Single error code. For this exception the value will be invalid_client .
        @[JSON::Field(key: "error")]
        getter error : String?

        # Human-readable text providing additional information, used to assist the client developer in
        # understanding the error that occurred.
        @[JSON::Field(key: "error_description")]
        getter error_description : String?

        def initialize(
          @error : String? = nil,
          @error_description : String? = nil
        )
        end
      end

      # Indicates that the client information sent in the request during registration is invalid.
      struct InvalidClientMetadataException
        include JSON::Serializable

        # Single error code. For this exception the value will be invalid_client_metadata .
        @[JSON::Field(key: "error")]
        getter error : String?

        # Human-readable text providing additional information, used to assist the client developer in
        # understanding the error that occurred.
        @[JSON::Field(key: "error_description")]
        getter error_description : String?

        def initialize(
          @error : String? = nil,
          @error_description : String? = nil
        )
        end
      end

      # Indicates that a request contains an invalid grant. This can occur if a client makes a CreateToken
      # request with an invalid grant type.
      struct InvalidGrantException
        include JSON::Serializable

        # Single error code. For this exception the value will be invalid_grant .
        @[JSON::Field(key: "error")]
        getter error : String?

        # Human-readable text providing additional information, used to assist the client developer in
        # understanding the error that occurred.
        @[JSON::Field(key: "error_description")]
        getter error_description : String?

        def initialize(
          @error : String? = nil,
          @error_description : String? = nil
        )
        end
      end

      # Indicates that one or more redirect URI in the request is not supported for this operation.
      struct InvalidRedirectUriException
        include JSON::Serializable

        # Single error code. For this exception the value will be invalid_redirect_uri .
        @[JSON::Field(key: "error")]
        getter error : String?

        # Human-readable text providing additional information, used to assist the client developer in
        # understanding the error that occurred.
        @[JSON::Field(key: "error_description")]
        getter error_description : String?

        def initialize(
          @error : String? = nil,
          @error_description : String? = nil
        )
        end
      end

      # Indicates that something is wrong with the input to the request. For example, a required parameter
      # might be missing or out of range.
      struct InvalidRequestException
        include JSON::Serializable

        # Single error code. For this exception the value will be invalid_request .
        @[JSON::Field(key: "error")]
        getter error : String?

        # Human-readable text providing additional information, used to assist the client developer in
        # understanding the error that occurred.
        @[JSON::Field(key: "error_description")]
        getter error_description : String?

        # A string that uniquely identifies a reason for the error.
        @[JSON::Field(key: "reason")]
        getter reason : String?

        def initialize(
          @error : String? = nil,
          @error_description : String? = nil,
          @reason : String? = nil
        )
        end
      end

      # Indicates that a token provided as input to the request was issued by and is only usable by calling
      # IAM Identity Center endpoints in another region.
      struct InvalidRequestRegionException
        include JSON::Serializable

        # Indicates the IAM Identity Center endpoint which the requester may call with this token.
        @[JSON::Field(key: "endpoint")]
        getter endpoint : String?

        # Single error code. For this exception the value will be invalid_request .
        @[JSON::Field(key: "error")]
        getter error : String?

        # Human-readable text providing additional information, used to assist the client developer in
        # understanding the error that occurred.
        @[JSON::Field(key: "error_description")]
        getter error_description : String?

        # Indicates the region which the requester may call with this token.
        @[JSON::Field(key: "region")]
        getter region : String?

        def initialize(
          @endpoint : String? = nil,
          @error : String? = nil,
          @error_description : String? = nil,
          @region : String? = nil
        )
        end
      end

      # Indicates that the scope provided in the request is invalid.
      struct InvalidScopeException
        include JSON::Serializable

        # Single error code. For this exception the value will be invalid_scope .
        @[JSON::Field(key: "error")]
        getter error : String?

        # Human-readable text providing additional information, used to assist the client developer in
        # understanding the error that occurred.
        @[JSON::Field(key: "error_description")]
        getter error_description : String?

        def initialize(
          @error : String? = nil,
          @error_description : String? = nil
        )
        end
      end

      struct RegisterClientRequest
        include JSON::Serializable

        # The friendly name of the client.
        @[JSON::Field(key: "clientName")]
        getter client_name : String

        # The type of client. The service supports only public as a client type. Anything other than public
        # will be rejected by the service.
        @[JSON::Field(key: "clientType")]
        getter client_type : String

        # This IAM Identity Center application ARN is used to define administrator-managed configuration for
        # public client access to resources. At authorization, the scopes, grants, and redirect URI available
        # to this client will be restricted by this application resource.
        @[JSON::Field(key: "entitledApplicationArn")]
        getter entitled_application_arn : String?

        # The list of OAuth 2.0 grant types that are defined by the client. This list is used to restrict the
        # token granting flows available to the client. Supports the following OAuth 2.0 grant types:
        # Authorization Code, Device Code, and Refresh Token. * Authorization Code - authorization_code *
        # Device Code - urn:ietf:params:oauth:grant-type:device_code * Refresh Token - refresh_token
        @[JSON::Field(key: "grantTypes")]
        getter grant_types : Array(String)?

        # The IAM Identity Center Issuer URL associated with an instance of IAM Identity Center. This value is
        # needed for user access to resources through the client.
        @[JSON::Field(key: "issuerUrl")]
        getter issuer_url : String?

        # The list of redirect URI that are defined by the client. At completion of authorization, this list
        # is used to restrict what locations the user agent can be redirected back to.
        @[JSON::Field(key: "redirectUris")]
        getter redirect_uris : Array(String)?

        # The list of scopes that are defined by the client. Upon authorization, this list is used to restrict
        # permissions when granting an access token.
        @[JSON::Field(key: "scopes")]
        getter scopes : Array(String)?

        def initialize(
          @client_name : String,
          @client_type : String,
          @entitled_application_arn : String? = nil,
          @grant_types : Array(String)? = nil,
          @issuer_url : String? = nil,
          @redirect_uris : Array(String)? = nil,
          @scopes : Array(String)? = nil
        )
        end
      end

      struct RegisterClientResponse
        include JSON::Serializable

        # An endpoint that the client can use to request authorization.
        @[JSON::Field(key: "authorizationEndpoint")]
        getter authorization_endpoint : String?

        # The unique identifier string for each client. This client uses this identifier to get authenticated
        # by the service in subsequent calls.
        @[JSON::Field(key: "clientId")]
        getter client_id : String?

        # Indicates the time at which the clientId and clientSecret were issued.
        @[JSON::Field(key: "clientIdIssuedAt")]
        getter client_id_issued_at : Int64?

        # A secret string generated for the client. The client will use this string to get authenticated by
        # the service in subsequent calls.
        @[JSON::Field(key: "clientSecret")]
        getter client_secret : String?

        # Indicates the time at which the clientId and clientSecret will become invalid.
        @[JSON::Field(key: "clientSecretExpiresAt")]
        getter client_secret_expires_at : Int64?

        # An endpoint that the client can use to create tokens.
        @[JSON::Field(key: "tokenEndpoint")]
        getter token_endpoint : String?

        def initialize(
          @authorization_endpoint : String? = nil,
          @client_id : String? = nil,
          @client_id_issued_at : Int64? = nil,
          @client_secret : String? = nil,
          @client_secret_expires_at : Int64? = nil,
          @token_endpoint : String? = nil
        )
        end
      end

      # Indicates that the client is making the request too frequently and is more than the service can
      # handle.
      struct SlowDownException
        include JSON::Serializable

        # Single error code. For this exception the value will be slow_down .
        @[JSON::Field(key: "error")]
        getter error : String?

        # Human-readable text providing additional information, used to assist the client developer in
        # understanding the error that occurred.
        @[JSON::Field(key: "error_description")]
        getter error_description : String?

        def initialize(
          @error : String? = nil,
          @error_description : String? = nil
        )
        end
      end

      struct StartDeviceAuthorizationRequest
        include JSON::Serializable

        # The unique identifier string for the client that is registered with IAM Identity Center. This value
        # should come from the persisted result of the RegisterClient API operation.
        @[JSON::Field(key: "clientId")]
        getter client_id : String

        # A secret string that is generated for the client. This value should come from the persisted result
        # of the RegisterClient API operation.
        @[JSON::Field(key: "clientSecret")]
        getter client_secret : String

        # The URL for the Amazon Web Services access portal. For more information, see Using the Amazon Web
        # Services access portal in the IAM Identity Center User Guide .
        @[JSON::Field(key: "startUrl")]
        getter start_url : String

        def initialize(
          @client_id : String,
          @client_secret : String,
          @start_url : String
        )
        end
      end

      struct StartDeviceAuthorizationResponse
        include JSON::Serializable

        # The short-lived code that is used by the device when polling for a session token.
        @[JSON::Field(key: "deviceCode")]
        getter device_code : String?

        # Indicates the number of seconds in which the verification code will become invalid.
        @[JSON::Field(key: "expiresIn")]
        getter expires_in : Int32?

        # Indicates the number of seconds the client must wait between attempts when polling for a session.
        @[JSON::Field(key: "interval")]
        getter interval : Int32?

        # A one-time user verification code. This is needed to authorize an in-use device.
        @[JSON::Field(key: "userCode")]
        getter user_code : String?

        # The URI of the verification page that takes the userCode to authorize the device.
        @[JSON::Field(key: "verificationUri")]
        getter verification_uri : String?

        # An alternate URL that the client can use to automatically launch a browser. This process skips the
        # manual step in which the user visits the verification page and enters their code.
        @[JSON::Field(key: "verificationUriComplete")]
        getter verification_uri_complete : String?

        def initialize(
          @device_code : String? = nil,
          @expires_in : Int32? = nil,
          @interval : Int32? = nil,
          @user_code : String? = nil,
          @verification_uri : String? = nil,
          @verification_uri_complete : String? = nil
        )
        end
      end

      # Indicates that the client is not currently authorized to make the request. This can happen when a
      # clientId is not issued for a public client.
      struct UnauthorizedClientException
        include JSON::Serializable

        # Single error code. For this exception the value will be unauthorized_client .
        @[JSON::Field(key: "error")]
        getter error : String?

        # Human-readable text providing additional information, used to assist the client developer in
        # understanding the error that occurred.
        @[JSON::Field(key: "error_description")]
        getter error_description : String?

        def initialize(
          @error : String? = nil,
          @error_description : String? = nil
        )
        end
      end

      # Indicates that the grant type in the request is not supported by the service.
      struct UnsupportedGrantTypeException
        include JSON::Serializable

        # Single error code. For this exception the value will be unsupported_grant_type .
        @[JSON::Field(key: "error")]
        getter error : String?

        # Human-readable text providing additional information, used to assist the client developer in
        # understanding the error that occurred.
        @[JSON::Field(key: "error_description")]
        getter error_description : String?

        def initialize(
          @error : String? = nil,
          @error_description : String? = nil
        )
        end
      end
    end
  end
end
