require "json"
require "file_utils"

module CrystalSdkGenerator
  module PartitionsGenerator
    SOURCE_PARTITIONS_JSON = File.expand_path("../../apis/partitions.json", __DIR__)

    def self.generate(output_root : String) : Nil
      raw = File.read(SOURCE_PARTITIONS_JSON)
      data = JSON.parse(raw).as_h
      partitions = data["partitions"]?.try(&.as_a) || [] of JSON::Any

      out_dir = File.join(output_root, "src", "runtime")
      FileUtils.mkdir_p(out_dir)
      File.write(File.join(out_dir, "partitions_data.cr"), render(partitions))
    end

    private def self.render(partitions : Array(JSON::Any)) : String
      first = partitions.first?.try(&.as_h)
      default_dns_suffix = dig_string(first, "dnsSuffix") ||
        first.try(&.["defaults"]?.try(&.as_h)).try(&.["dnsSuffix"]?.try(&.as_s)) ||
        "amazonaws.com"

      String.build do |io|
        io << "# Generated by build_tools/crystal_sdk_generator/partitions_generator.cr. Do not edit.\n"
        io << "module Aws\n"
        io << "  module Runtime\n"
        io << "    module PartitionsData\n"
        io << "      record Partition,\n"
        io << "        regions : Array(String),\n"
        io << "        region_regex : Regex,\n"
        io << "        dns_suffix : String,\n"
        io << "        dualstack_dns_suffix : String,\n"
        io << "        supports_dualstack : Bool,\n"
        io << "        supports_fips : Bool\n"
        io << "\n"
        io << "      DEFAULT_DNS_SUFFIX = "
        io << default_dns_suffix.inspect
        io << "\n\n"
        io << "      ALL = [\n"
        partitions.each do |partition_any|
          render_partition(io, partition_any.as_h)
        end
        io << "      ] of Partition\n"
        io << "    end\n"
        io << "  end\n"
        io << "end\n"
      end
    end

    private def self.render_partition(io : IO, partition : Hash(String, JSON::Any)) : Nil
      regions = partition["regions"]?.try(&.as_h).try(&.keys).try(&.sort) || [] of String
      region_regex = partition["regionRegex"]?.try(&.as_s) || ""

      defaults = partition["defaults"]?.try(&.as_h)
      variants = defaults.try(&.["variants"]?.try(&.as_a)) || [] of JSON::Any

      dns_suffix = partition["dnsSuffix"]?.try(&.as_s) ||
        defaults.try(&.["dnsSuffix"]?.try(&.as_s)) || ""

      dualstack_variant = variants.find do |variant_any|
        tags = variant_tags(variant_any)
        tags.includes?("dualstack") && !tags.includes?("fips")
      end
      dualstack_dns_suffix = dualstack_variant.try(&.as_h["dnsSuffix"]?.try(&.as_s)) || dns_suffix

      supports_dualstack = variants.any? { |v| variant_tags(v).includes?("dualstack") }
      supports_fips = variants.any? { |v| variant_tags(v).includes?("fips") }

      io << "        Partition.new(\n"
      io << "          regions: ["
      regions.each_with_index do |region, idx|
        io << ", " if idx > 0
        io << region.inspect
      end
      io << "],\n"
      io << "          region_regex: Regex.new(" << region_regex.inspect << "),\n"
      io << "          dns_suffix: " << dns_suffix.inspect << ",\n"
      io << "          dualstack_dns_suffix: " << dualstack_dns_suffix.inspect << ",\n"
      io << "          supports_dualstack: " << supports_dualstack << ",\n"
      io << "          supports_fips: " << supports_fips << ",\n"
      io << "        ),\n"
    end

    private def self.variant_tags(variant : JSON::Any) : Array(String)
      variant.as_h["tags"]?.try(&.as_a.map(&.as_s)) || [] of String
    end

    private def self.dig_string(hash : Hash(String, JSON::Any)?, key : String) : String?
      hash.try(&.[key]?.try(&.as_s))
    end
  end
end
