require "json"
require "time"

module Aws
  module Identitystore
    module Types

      # You do not have sufficient access to perform this action.

      struct AccessDeniedException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        # Indicates the reason for an access denial when returned by KMS while accessing a Customer Managed
        # KMS key. For non-KMS access-denied errors, this field is not included.

        @[JSON::Field(key: "Reason")]
        getter reason : String?

        # The identifier for each request. This value is a globally unique ID that is generated by the
        # identity store service for each sent request, and is then returned inside the exception if the
        # request fails.

        @[JSON::Field(key: "RequestId")]
        getter request_id : String?

        def initialize(
          @message : String? = nil,
          @reason : String? = nil,
          @request_id : String? = nil
        )
        end
      end

      # The address associated with the specified user.

      struct Address
        include JSON::Serializable

        # The country of the address.

        @[JSON::Field(key: "Country")]
        getter country : String?

        # A string containing a formatted version of the address for display.

        @[JSON::Field(key: "Formatted")]
        getter formatted : String?

        # A string of the address locality.

        @[JSON::Field(key: "Locality")]
        getter locality : String?

        # The postal code of the address.

        @[JSON::Field(key: "PostalCode")]
        getter postal_code : String?

        # A Boolean value representing whether this is the primary address for the associated resource.

        @[JSON::Field(key: "Primary")]
        getter primary : Bool?

        # The region of the address.

        @[JSON::Field(key: "Region")]
        getter region : String?

        # The street of the address.

        @[JSON::Field(key: "StreetAddress")]
        getter street_address : String?

        # A string representing the type of address. For example, "Home."

        @[JSON::Field(key: "Type")]
        getter type : String?

        def initialize(
          @country : String? = nil,
          @formatted : String? = nil,
          @locality : String? = nil,
          @postal_code : String? = nil,
          @primary : Bool? = nil,
          @region : String? = nil,
          @street_address : String? = nil,
          @type : String? = nil
        )
        end
      end

      # A unique identifier for a user or group that is not the primary identifier. This value can be an
      # identifier from an external identity provider (IdP) that is associated with the user, the group, or
      # a unique attribute.

      struct AlternateIdentifier
        include JSON::Serializable

        # The identifier issued to this resource by an external identity provider.

        @[JSON::Field(key: "ExternalId")]
        getter external_id : Types::ExternalId?

        # An entity attribute that's unique to a specific entity.

        @[JSON::Field(key: "UniqueAttribute")]
        getter unique_attribute : Types::UniqueAttribute?

        def initialize(
          @external_id : Types::ExternalId? = nil,
          @unique_attribute : Types::UniqueAttribute? = nil
        )
        end
      end

      # An operation that applies to the requested group. This operation might add, replace, or remove an
      # attribute.

      struct AttributeOperation
        include JSON::Serializable

        # A string representation of the path to a given attribute or sub-attribute. Supports JMESPath.

        @[JSON::Field(key: "AttributePath")]
        getter attribute_path : String

        # The value of the attribute. This is a Document type. This type is not supported by Java V1, Go V1,
        # and older versions of the CLI.

        @[JSON::Field(key: "AttributeValue")]
        getter attribute_value : Types::AttributeValue?

        def initialize(
          @attribute_path : String,
          @attribute_value : Types::AttributeValue? = nil
        )
        end
      end

      # The value of the attribute. This is a Document type. This type is not supported by Java V1, Go V1,
      # and older versions of the CLI.

      struct AttributeValue
        include JSON::Serializable

        def initialize
        end
      end

      # This request cannot be completed for one of the following reasons: Performing the requested
      # operation would violate an existing uniqueness claim in the identity store. Resolve the conflict
      # before retrying this request. The requested resource was being concurrently modified by another
      # request.

      struct ConflictException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        # Indicates the reason for a conflict error when the service is unable to access a Customer Managed
        # KMS key. For non-KMS permission errors, this field is not included.

        @[JSON::Field(key: "Reason")]
        getter reason : String?

        # The identifier for each request. This value is a globally unique ID that is generated by the
        # identity store service for each sent request, and is then returned inside the exception if the
        # request fails.

        @[JSON::Field(key: "RequestId")]
        getter request_id : String?

        def initialize(
          @message : String? = nil,
          @reason : String? = nil,
          @request_id : String? = nil
        )
        end
      end


      struct CreateGroupMembershipRequest
        include JSON::Serializable

        # The identifier for a group in the identity store.

        @[JSON::Field(key: "GroupId")]
        getter group_id : String

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # An object that contains the identifier of a group member. Setting the UserID field to the specific
        # identifier for a user indicates that the user is a member of the group.

        @[JSON::Field(key: "MemberId")]
        getter member_id : Types::MemberId

        def initialize(
          @group_id : String,
          @identity_store_id : String,
          @member_id : Types::MemberId
        )
        end
      end


      struct CreateGroupMembershipResponse
        include JSON::Serializable

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # The identifier for a newly created GroupMembership in an identity store.

        @[JSON::Field(key: "MembershipId")]
        getter membership_id : String

        def initialize(
          @identity_store_id : String,
          @membership_id : String
        )
        end
      end


      struct CreateGroupRequest
        include JSON::Serializable

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # A string containing the description of the group.

        @[JSON::Field(key: "Description")]
        getter description : String?

        # A string containing the name of the group. This value is commonly displayed when the group is
        # referenced. Administrator and AWSAdministrators are reserved names and can't be used for users or
        # groups.

        @[JSON::Field(key: "DisplayName")]
        getter display_name : String?

        def initialize(
          @identity_store_id : String,
          @description : String? = nil,
          @display_name : String? = nil
        )
        end
      end


      struct CreateGroupResponse
        include JSON::Serializable

        # The identifier of the newly created group in the identity store.

        @[JSON::Field(key: "GroupId")]
        getter group_id : String

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        def initialize(
          @group_id : String,
          @identity_store_id : String
        )
        end
      end


      struct CreateUserRequest
        include JSON::Serializable

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # A list of Address objects containing addresses associated with the user.

        @[JSON::Field(key: "Addresses")]
        getter addresses : Array(Types::Address)?

        # The user's birthdate in YYYY-MM-DD format. This field supports standard date format for storing
        # personal information.

        @[JSON::Field(key: "Birthdate")]
        getter birthdate : String?

        # A string containing the name of the user. This value is typically formatted for display when the
        # user is referenced. For example, "John Doe." When used in IAM Identity Center, this parameter is
        # required.

        @[JSON::Field(key: "DisplayName")]
        getter display_name : String?

        # A list of Email objects containing email addresses associated with the user.

        @[JSON::Field(key: "Emails")]
        getter emails : Array(Types::Email)?

        # A map with additional attribute extensions for the user. Each map key corresponds to an extension
        # name, while map values represent extension data in Document type (not supported by Java V1, Go V1
        # and older versions of the CLI). aws:identitystore:enterprise is the only supported extension name.

        @[JSON::Field(key: "Extensions")]
        getter extensions : Hash(String, Types::AttributeValue)?

        # A string containing the geographical region or location of the user.

        @[JSON::Field(key: "Locale")]
        getter locale : String?

        # An object containing the name of the user. When used in IAM Identity Center, this parameter is
        # required.

        @[JSON::Field(key: "Name")]
        getter name : Types::Name?

        # A string containing an alternate name for the user.

        @[JSON::Field(key: "NickName")]
        getter nick_name : String?

        # A list of PhoneNumber objects containing phone numbers associated with the user.

        @[JSON::Field(key: "PhoneNumbers")]
        getter phone_numbers : Array(Types::PhoneNumber)?

        # A list of photos associated with the user. You can add up to 3 photos per user. Each photo can
        # include a value, type, display name, and primary designation.

        @[JSON::Field(key: "Photos")]
        getter photos : Array(Types::Photo)?

        # A string containing the preferred language of the user. For example, "American English" or "en-us."

        @[JSON::Field(key: "PreferredLanguage")]
        getter preferred_language : String?

        # A string containing a URL that might be associated with the user.

        @[JSON::Field(key: "ProfileUrl")]
        getter profile_url : String?

        # A list of Role objects containing roles associated with the user.

        @[JSON::Field(key: "Roles")]
        getter roles : Array(Types::Role)?

        # A string containing the time zone of the user.

        @[JSON::Field(key: "Timezone")]
        getter timezone : String?

        # A string containing the title of the user. Possible values are left unspecified. The value can vary
        # based on your specific use case.

        @[JSON::Field(key: "Title")]
        getter title : String?

        # A unique string used to identify the user. The length limit is 128 characters. This value can
        # consist of letters, accented characters, symbols, numbers, and punctuation. This value is specified
        # at the time the user is created and stored as an attribute of the user object in the identity store.
        # Administrator and AWSAdministrators are reserved names and can't be used for users or groups.

        @[JSON::Field(key: "UserName")]
        getter user_name : String?

        # A string indicating the type of user. Possible values are left unspecified. The value can vary based
        # on your specific use case.

        @[JSON::Field(key: "UserType")]
        getter user_type : String?

        # The user's personal website or blog URL. This field allows users to provide a link to their personal
        # or professional website.

        @[JSON::Field(key: "Website")]
        getter website : String?

        def initialize(
          @identity_store_id : String,
          @addresses : Array(Types::Address)? = nil,
          @birthdate : String? = nil,
          @display_name : String? = nil,
          @emails : Array(Types::Email)? = nil,
          @extensions : Hash(String, Types::AttributeValue)? = nil,
          @locale : String? = nil,
          @name : Types::Name? = nil,
          @nick_name : String? = nil,
          @phone_numbers : Array(Types::PhoneNumber)? = nil,
          @photos : Array(Types::Photo)? = nil,
          @preferred_language : String? = nil,
          @profile_url : String? = nil,
          @roles : Array(Types::Role)? = nil,
          @timezone : String? = nil,
          @title : String? = nil,
          @user_name : String? = nil,
          @user_type : String? = nil,
          @website : String? = nil
        )
        end
      end


      struct CreateUserResponse
        include JSON::Serializable

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # The identifier of the newly created user in the identity store.

        @[JSON::Field(key: "UserId")]
        getter user_id : String

        def initialize(
          @identity_store_id : String,
          @user_id : String
        )
        end
      end


      struct DeleteGroupMembershipRequest
        include JSON::Serializable

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # The identifier for a GroupMembership in an identity store.

        @[JSON::Field(key: "MembershipId")]
        getter membership_id : String

        def initialize(
          @identity_store_id : String,
          @membership_id : String
        )
        end
      end


      struct DeleteGroupMembershipResponse
        include JSON::Serializable

        def initialize
        end
      end


      struct DeleteGroupRequest
        include JSON::Serializable

        # The identifier for a group in the identity store.

        @[JSON::Field(key: "GroupId")]
        getter group_id : String

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        def initialize(
          @group_id : String,
          @identity_store_id : String
        )
        end
      end


      struct DeleteGroupResponse
        include JSON::Serializable

        def initialize
        end
      end


      struct DeleteUserRequest
        include JSON::Serializable

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # The identifier for a user in the identity store.

        @[JSON::Field(key: "UserId")]
        getter user_id : String

        def initialize(
          @identity_store_id : String,
          @user_id : String
        )
        end
      end


      struct DeleteUserResponse
        include JSON::Serializable

        def initialize
        end
      end


      struct DescribeGroupMembershipRequest
        include JSON::Serializable

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # The identifier for a GroupMembership in an identity store.

        @[JSON::Field(key: "MembershipId")]
        getter membership_id : String

        def initialize(
          @identity_store_id : String,
          @membership_id : String
        )
        end
      end


      struct DescribeGroupMembershipResponse
        include JSON::Serializable

        # The identifier for a group in the identity store.

        @[JSON::Field(key: "GroupId")]
        getter group_id : String

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String


        @[JSON::Field(key: "MemberId")]
        getter member_id : Types::MemberId

        # The identifier for a GroupMembership in an identity store.

        @[JSON::Field(key: "MembershipId")]
        getter membership_id : String

        # The date and time the group membership was created.

        @[JSON::Field(key: "CreatedAt", converter: Aws::Runtime::UnixTimestampConverter)]
        getter created_at : Time?

        # The identifier of the user or system that created the group membership.

        @[JSON::Field(key: "CreatedBy")]
        getter created_by : String?

        # The date and time the group membership was last updated.

        @[JSON::Field(key: "UpdatedAt", converter: Aws::Runtime::UnixTimestampConverter)]
        getter updated_at : Time?

        # The identifier of the user or system that last updated the group membership.

        @[JSON::Field(key: "UpdatedBy")]
        getter updated_by : String?

        def initialize(
          @group_id : String,
          @identity_store_id : String,
          @member_id : Types::MemberId,
          @membership_id : String,
          @created_at : Time? = nil,
          @created_by : String? = nil,
          @updated_at : Time? = nil,
          @updated_by : String? = nil
        )
        end
      end


      struct DescribeGroupRequest
        include JSON::Serializable

        # The identifier for a group in the identity store.

        @[JSON::Field(key: "GroupId")]
        getter group_id : String

        # The globally unique identifier for the identity store, such as d-1234567890 . In this example, d- is
        # a fixed prefix, and 1234567890 is a randomly generated string that contains numbers and lower case
        # letters. This value is generated at the time that a new identity store is created.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        def initialize(
          @group_id : String,
          @identity_store_id : String
        )
        end
      end


      struct DescribeGroupResponse
        include JSON::Serializable

        # The identifier for a group in the identity store.

        @[JSON::Field(key: "GroupId")]
        getter group_id : String

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # The date and time the group was created.

        @[JSON::Field(key: "CreatedAt", converter: Aws::Runtime::UnixTimestampConverter)]
        getter created_at : Time?

        # The identifier of the user or system that created the group.

        @[JSON::Field(key: "CreatedBy")]
        getter created_by : String?

        # A string containing a description of the group.

        @[JSON::Field(key: "Description")]
        getter description : String?

        # The group’s display name value. The length limit is 1,024 characters. This value can consist of
        # letters, accented characters, symbols, numbers, punctuation, tab, new line, carriage return, space,
        # and nonbreaking space in this attribute. This value is specified at the time that the group is
        # created and stored as an attribute of the group object in the identity store.

        @[JSON::Field(key: "DisplayName")]
        getter display_name : String?

        # A list of ExternalId objects that contains the identifiers issued to this resource by an external
        # identity provider.

        @[JSON::Field(key: "ExternalIds")]
        getter external_ids : Array(Types::ExternalId)?

        # The date and time the group was last updated.

        @[JSON::Field(key: "UpdatedAt", converter: Aws::Runtime::UnixTimestampConverter)]
        getter updated_at : Time?

        # The identifier of the user or system that last updated the group.

        @[JSON::Field(key: "UpdatedBy")]
        getter updated_by : String?

        def initialize(
          @group_id : String,
          @identity_store_id : String,
          @created_at : Time? = nil,
          @created_by : String? = nil,
          @description : String? = nil,
          @display_name : String? = nil,
          @external_ids : Array(Types::ExternalId)? = nil,
          @updated_at : Time? = nil,
          @updated_by : String? = nil
        )
        end
      end


      struct DescribeUserRequest
        include JSON::Serializable

        # The globally unique identifier for the identity store, such as d-1234567890 . In this example, d- is
        # a fixed prefix, and 1234567890 is a randomly generated string that contains numbers and lower case
        # letters. This value is generated at the time that a new identity store is created.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # The identifier for a user in the identity store.

        @[JSON::Field(key: "UserId")]
        getter user_id : String

        # A collection of extension names indicating what extensions the service should retrieve alongside
        # other user attributes. aws:identitystore:enterprise is the only supported extension name.

        @[JSON::Field(key: "Extensions")]
        getter extensions : Array(String)?

        def initialize(
          @identity_store_id : String,
          @user_id : String,
          @extensions : Array(String)? = nil
        )
        end
      end


      struct DescribeUserResponse
        include JSON::Serializable

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # The identifier for a user in the identity store.

        @[JSON::Field(key: "UserId")]
        getter user_id : String

        # The physical address of the user.

        @[JSON::Field(key: "Addresses")]
        getter addresses : Array(Types::Address)?

        # The user's birthdate in YYYY-MM-DD format. This field returns the stored birthdate information for
        # the user.

        @[JSON::Field(key: "Birthdate")]
        getter birthdate : String?

        # The date and time the user was created.

        @[JSON::Field(key: "CreatedAt", converter: Aws::Runtime::UnixTimestampConverter)]
        getter created_at : Time?

        # The identifier of the user or system that created the user.

        @[JSON::Field(key: "CreatedBy")]
        getter created_by : String?

        # The display name of the user.

        @[JSON::Field(key: "DisplayName")]
        getter display_name : String?

        # The email address of the user.

        @[JSON::Field(key: "Emails")]
        getter emails : Array(Types::Email)?

        # A map of explicitly requested attribute extensions associated with the user. Not populated if the
        # user has no requested extensions.

        @[JSON::Field(key: "Extensions")]
        getter extensions : Hash(String, Types::AttributeValue)?

        # A list of ExternalId objects that contains the identifiers issued to this resource by an external
        # identity provider.

        @[JSON::Field(key: "ExternalIds")]
        getter external_ids : Array(Types::ExternalId)?

        # A string containing the geographical region or location of the user.

        @[JSON::Field(key: "Locale")]
        getter locale : String?

        # The name of the user.

        @[JSON::Field(key: "Name")]
        getter name : Types::Name?

        # An alternative descriptive name for the user.

        @[JSON::Field(key: "NickName")]
        getter nick_name : String?

        # A list of PhoneNumber objects associated with a user.

        @[JSON::Field(key: "PhoneNumbers")]
        getter phone_numbers : Array(Types::PhoneNumber)?

        # A list of photos associated with the user. Returns up to 3 photos with their associated metadata
        # including type, display name, and primary designation.

        @[JSON::Field(key: "Photos")]
        getter photos : Array(Types::Photo)?

        # The preferred language of the user.

        @[JSON::Field(key: "PreferredLanguage")]
        getter preferred_language : String?

        # A URL link for the user's profile.

        @[JSON::Field(key: "ProfileUrl")]
        getter profile_url : String?

        # The roles of the user.

        @[JSON::Field(key: "Roles")]
        getter roles : Array(Types::Role)?

        # The time zone for a user.

        @[JSON::Field(key: "Timezone")]
        getter timezone : String?

        # A string containing the title of the user.

        @[JSON::Field(key: "Title")]
        getter title : String?

        # The date and time the user was last updated.

        @[JSON::Field(key: "UpdatedAt", converter: Aws::Runtime::UnixTimestampConverter)]
        getter updated_at : Time?

        # The identifier of the user or system that last updated the user.

        @[JSON::Field(key: "UpdatedBy")]
        getter updated_by : String?

        # A unique string used to identify the user. The length limit is 128 characters. This value can
        # consist of letters, accented characters, symbols, numbers, and punctuation. This value is specified
        # at the time the user is created and stored as an attribute of the user object in the identity store.

        @[JSON::Field(key: "UserName")]
        getter user_name : String?

        # The current status of the user account.

        @[JSON::Field(key: "UserStatus")]
        getter user_status : String?

        # A string indicating the type of user.

        @[JSON::Field(key: "UserType")]
        getter user_type : String?

        # The user's personal website or blog URL. Returns the stored website information for the user.

        @[JSON::Field(key: "Website")]
        getter website : String?

        def initialize(
          @identity_store_id : String,
          @user_id : String,
          @addresses : Array(Types::Address)? = nil,
          @birthdate : String? = nil,
          @created_at : Time? = nil,
          @created_by : String? = nil,
          @display_name : String? = nil,
          @emails : Array(Types::Email)? = nil,
          @extensions : Hash(String, Types::AttributeValue)? = nil,
          @external_ids : Array(Types::ExternalId)? = nil,
          @locale : String? = nil,
          @name : Types::Name? = nil,
          @nick_name : String? = nil,
          @phone_numbers : Array(Types::PhoneNumber)? = nil,
          @photos : Array(Types::Photo)? = nil,
          @preferred_language : String? = nil,
          @profile_url : String? = nil,
          @roles : Array(Types::Role)? = nil,
          @timezone : String? = nil,
          @title : String? = nil,
          @updated_at : Time? = nil,
          @updated_by : String? = nil,
          @user_name : String? = nil,
          @user_status : String? = nil,
          @user_type : String? = nil,
          @website : String? = nil
        )
        end
      end

      # The email address associated with the user.

      struct Email
        include JSON::Serializable

        # A Boolean value representing whether this is the primary email address for the associated resource.

        @[JSON::Field(key: "Primary")]
        getter primary : Bool?

        # A string representing the type of address. For example, "Work."

        @[JSON::Field(key: "Type")]
        getter type : String?

        # A string containing an email address. For example, "johndoe@amazon.com."

        @[JSON::Field(key: "Value")]
        getter value : String?

        def initialize(
          @primary : Bool? = nil,
          @type : String? = nil,
          @value : String? = nil
        )
        end
      end

      # The identifier issued to this resource by an external identity provider.

      struct ExternalId
        include JSON::Serializable

        # The identifier issued to this resource by an external identity provider.

        @[JSON::Field(key: "Id")]
        getter id : String

        # The issuer for an external identifier.

        @[JSON::Field(key: "Issuer")]
        getter issuer : String

        def initialize(
          @id : String,
          @issuer : String
        )
        end
      end

      # A query filter used by ListUsers and ListGroups . This filter object provides the attribute name and
      # attribute value to search users or groups.

      struct Filter
        include JSON::Serializable

        # The attribute path that is used to specify which attribute name to search. Length limit is 255
        # characters. For example, UserName is a valid attribute path for the ListUsers API, and DisplayName
        # is a valid attribute path for the ListGroups API.

        @[JSON::Field(key: "AttributePath")]
        getter attribute_path : String

        # Represents the data for an attribute. Each attribute value is described as a name-value pair.

        @[JSON::Field(key: "AttributeValue")]
        getter attribute_value : String

        def initialize(
          @attribute_path : String,
          @attribute_value : String
        )
        end
      end


      struct GetGroupIdRequest
        include JSON::Serializable

        # A unique identifier for a user or group that is not the primary identifier. This value can be an
        # identifier from an external identity provider (IdP) that is associated with the user, the group, or
        # a unique attribute. For the unique attribute, the only valid path is displayName .

        @[JSON::Field(key: "AlternateIdentifier")]
        getter alternate_identifier : Types::AlternateIdentifier

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        def initialize(
          @alternate_identifier : Types::AlternateIdentifier,
          @identity_store_id : String
        )
        end
      end


      struct GetGroupIdResponse
        include JSON::Serializable

        # The identifier for a group in the identity store.

        @[JSON::Field(key: "GroupId")]
        getter group_id : String

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        def initialize(
          @group_id : String,
          @identity_store_id : String
        )
        end
      end


      struct GetGroupMembershipIdRequest
        include JSON::Serializable

        # The identifier for a group in the identity store.

        @[JSON::Field(key: "GroupId")]
        getter group_id : String

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # An object that contains the identifier of a group member. Setting the UserID field to the specific
        # identifier for a user indicates that the user is a member of the group.

        @[JSON::Field(key: "MemberId")]
        getter member_id : Types::MemberId

        def initialize(
          @group_id : String,
          @identity_store_id : String,
          @member_id : Types::MemberId
        )
        end
      end


      struct GetGroupMembershipIdResponse
        include JSON::Serializable

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # The identifier for a GroupMembership in an identity store.

        @[JSON::Field(key: "MembershipId")]
        getter membership_id : String

        def initialize(
          @identity_store_id : String,
          @membership_id : String
        )
        end
      end


      struct GetUserIdRequest
        include JSON::Serializable

        # A unique identifier for a user or group that is not the primary identifier. This value can be an
        # identifier from an external identity provider (IdP) that is associated with the user, the group, or
        # a unique attribute. For the unique attribute, the only valid paths are userName and emails.value .

        @[JSON::Field(key: "AlternateIdentifier")]
        getter alternate_identifier : Types::AlternateIdentifier

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        def initialize(
          @alternate_identifier : Types::AlternateIdentifier,
          @identity_store_id : String
        )
        end
      end


      struct GetUserIdResponse
        include JSON::Serializable

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # The identifier for a user in the identity store.

        @[JSON::Field(key: "UserId")]
        getter user_id : String

        def initialize(
          @identity_store_id : String,
          @user_id : String
        )
        end
      end

      # A group object that contains the metadata and attributes for a specified group.

      struct Group
        include JSON::Serializable

        # The identifier for a group in the identity store.

        @[JSON::Field(key: "GroupId")]
        getter group_id : String

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # The date and time the group was created.

        @[JSON::Field(key: "CreatedAt", converter: Aws::Runtime::UnixTimestampConverter)]
        getter created_at : Time?

        # The identifier of the user or system that created the group.

        @[JSON::Field(key: "CreatedBy")]
        getter created_by : String?

        # A string containing a description of the specified group.

        @[JSON::Field(key: "Description")]
        getter description : String?

        # The display name value for the group. The length limit is 1,024 characters. This value can consist
        # of letters, accented characters, symbols, numbers, punctuation, tab, new line, carriage return,
        # space, and nonbreaking space in this attribute. This value is specified at the time the group is
        # created and stored as an attribute of the group object in the identity store. Prefix search supports
        # a maximum of 1,000 characters for the string.

        @[JSON::Field(key: "DisplayName")]
        getter display_name : String?

        # A list of ExternalId objects that contains the identifiers issued to this resource by an external
        # identity provider.

        @[JSON::Field(key: "ExternalIds")]
        getter external_ids : Array(Types::ExternalId)?

        # The date and time the group was last updated.

        @[JSON::Field(key: "UpdatedAt", converter: Aws::Runtime::UnixTimestampConverter)]
        getter updated_at : Time?

        # The identifier of the user or system that last updated the group.

        @[JSON::Field(key: "UpdatedBy")]
        getter updated_by : String?

        def initialize(
          @group_id : String,
          @identity_store_id : String,
          @created_at : Time? = nil,
          @created_by : String? = nil,
          @description : String? = nil,
          @display_name : String? = nil,
          @external_ids : Array(Types::ExternalId)? = nil,
          @updated_at : Time? = nil,
          @updated_by : String? = nil
        )
        end
      end

      # Contains the identifiers for a group, a group member, and a GroupMembership object in the identity
      # store.

      struct GroupMembership
        include JSON::Serializable

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # The date and time the group membership was created.

        @[JSON::Field(key: "CreatedAt", converter: Aws::Runtime::UnixTimestampConverter)]
        getter created_at : Time?

        # The identifier of the user or system that created the group membership.

        @[JSON::Field(key: "CreatedBy")]
        getter created_by : String?

        # The identifier for a group in the identity store.

        @[JSON::Field(key: "GroupId")]
        getter group_id : String?

        # An object that contains the identifier of a group member. Setting the UserID field to the specific
        # identifier for a user indicates that the user is a member of the group.

        @[JSON::Field(key: "MemberId")]
        getter member_id : Types::MemberId?

        # The identifier for a GroupMembership object in an identity store.

        @[JSON::Field(key: "MembershipId")]
        getter membership_id : String?

        # The date and time the group membership was last updated.

        @[JSON::Field(key: "UpdatedAt", converter: Aws::Runtime::UnixTimestampConverter)]
        getter updated_at : Time?

        # The identifier of the user or system that last updated the group membership.

        @[JSON::Field(key: "UpdatedBy")]
        getter updated_by : String?

        def initialize(
          @identity_store_id : String,
          @created_at : Time? = nil,
          @created_by : String? = nil,
          @group_id : String? = nil,
          @member_id : Types::MemberId? = nil,
          @membership_id : String? = nil,
          @updated_at : Time? = nil,
          @updated_by : String? = nil
        )
        end
      end

      # Indicates whether a resource is a member of a group in the identity store.

      struct GroupMembershipExistenceResult
        include JSON::Serializable

        # The identifier for a group in the identity store.

        @[JSON::Field(key: "GroupId")]
        getter group_id : String?

        # An object that contains the identifier of a group member. Setting the UserID field to the specific
        # identifier for a user indicates that the user is a member of the group.

        @[JSON::Field(key: "MemberId")]
        getter member_id : Types::MemberId?

        # Indicates whether a membership relation exists or not.

        @[JSON::Field(key: "MembershipExists")]
        getter membership_exists : Bool?

        def initialize(
          @group_id : String? = nil,
          @member_id : Types::MemberId? = nil,
          @membership_exists : Bool? = nil
        )
        end
      end

      # The request processing has failed because of an unknown error, exception or failure with an internal
      # server.

      struct InternalServerException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        # The identifier for each request. This value is a globally unique ID that is generated by the
        # identity store service for each sent request, and is then returned inside the exception if the
        # request fails.

        @[JSON::Field(key: "RequestId")]
        getter request_id : String?

        # The number of seconds to wait before retrying the next request.

        @[JSON::Field(key: "RetryAfterSeconds")]
        getter retry_after_seconds : Int32?

        def initialize(
          @message : String? = nil,
          @request_id : String? = nil,
          @retry_after_seconds : Int32? = nil
        )
        end
      end


      struct IsMemberInGroupsRequest
        include JSON::Serializable

        # A list of identifiers for groups in the identity store.

        @[JSON::Field(key: "GroupIds")]
        getter group_ids : Array(String)

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # An object containing the identifier of a group member.

        @[JSON::Field(key: "MemberId")]
        getter member_id : Types::MemberId

        def initialize(
          @group_ids : Array(String),
          @identity_store_id : String,
          @member_id : Types::MemberId
        )
        end
      end


      struct IsMemberInGroupsResponse
        include JSON::Serializable

        # A list containing the results of membership existence checks.

        @[JSON::Field(key: "Results")]
        getter results : Array(Types::GroupMembershipExistenceResult)

        def initialize(
          @results : Array(Types::GroupMembershipExistenceResult)
        )
        end
      end


      struct ListGroupMembershipsForMemberRequest
        include JSON::Serializable

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # An object that contains the identifier of a group member. Setting the UserID field to the specific
        # identifier for a user indicates that the user is a member of the group.

        @[JSON::Field(key: "MemberId")]
        getter member_id : Types::MemberId

        # The maximum number of results to be returned per request. This parameter is used in the ListUsers
        # and ListGroups requests to specify how many results to return in one page. The length limit is 50
        # characters.

        @[JSON::Field(key: "MaxResults")]
        getter max_results : Int32?

        # The pagination token used for the ListUsers , ListGroups , and ListGroupMemberships API operations.
        # This value is generated by the identity store service. It is returned in the API response if the
        # total results are more than the size of one page. This token is also returned when it is used in the
        # API request to search for the next page.

        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @identity_store_id : String,
          @member_id : Types::MemberId,
          @max_results : Int32? = nil,
          @next_token : String? = nil
        )
        end
      end


      struct ListGroupMembershipsForMemberResponse
        include JSON::Serializable

        # A list of GroupMembership objects in the group for a specified member.

        @[JSON::Field(key: "GroupMemberships")]
        getter group_memberships : Array(Types::GroupMembership)

        # The pagination token used for the ListUsers , ListGroups , and ListGroupMemberships API operations.
        # This value is generated by the identity store service. It is returned in the API response if the
        # total results are more than the size of one page. This token is also returned when it is used in the
        # API request to search for the next page.

        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @group_memberships : Array(Types::GroupMembership),
          @next_token : String? = nil
        )
        end
      end


      struct ListGroupMembershipsRequest
        include JSON::Serializable

        # The identifier for a group in the identity store.

        @[JSON::Field(key: "GroupId")]
        getter group_id : String

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # The maximum number of results to be returned per request. This parameter is used in all List
        # requests to specify how many results to return in one page.

        @[JSON::Field(key: "MaxResults")]
        getter max_results : Int32?

        # The pagination token used for the ListUsers , ListGroups and ListGroupMemberships API operations.
        # This value is generated by the identity store service. It is returned in the API response if the
        # total results are more than the size of one page. This token is also returned when it is used in the
        # API request to search for the next page.

        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @group_id : String,
          @identity_store_id : String,
          @max_results : Int32? = nil,
          @next_token : String? = nil
        )
        end
      end


      struct ListGroupMembershipsResponse
        include JSON::Serializable

        # A list of GroupMembership objects in the group.

        @[JSON::Field(key: "GroupMemberships")]
        getter group_memberships : Array(Types::GroupMembership)

        # The pagination token used for the ListUsers , ListGroups , and ListGroupMemberships API operations.
        # This value is generated by the identity store service. It is returned in the API response if the
        # total results are more than the size of one page. This token is also returned when it is used in the
        # API request to search for the next page.

        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @group_memberships : Array(Types::GroupMembership),
          @next_token : String? = nil
        )
        end
      end


      struct ListGroupsRequest
        include JSON::Serializable

        # The globally unique identifier for the identity store, such as d-1234567890 . In this example, d- is
        # a fixed prefix, and 1234567890 is a randomly generated string that contains numbers and lower case
        # letters. This value is generated at the time that a new identity store is created.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # A list of Filter objects, which is used in the ListUsers and ListGroups requests.

        @[JSON::Field(key: "Filters")]
        getter filters : Array(Types::Filter)?

        # The maximum number of results to be returned per request. This parameter is used in the ListUsers
        # and ListGroups requests to specify how many results to return in one page. The length limit is 50
        # characters.

        @[JSON::Field(key: "MaxResults")]
        getter max_results : Int32?

        # The pagination token used for the ListUsers and ListGroups API operations. This value is generated
        # by the identity store service. It is returned in the API response if the total results are more than
        # the size of one page. This token is also returned when it is used in the API request to search for
        # the next page.

        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @identity_store_id : String,
          @filters : Array(Types::Filter)? = nil,
          @max_results : Int32? = nil,
          @next_token : String? = nil
        )
        end
      end


      struct ListGroupsResponse
        include JSON::Serializable

        # A list of Group objects in the identity store.

        @[JSON::Field(key: "Groups")]
        getter groups : Array(Types::Group)

        # The pagination token used for the ListUsers and ListGroups API operations. This value is generated
        # by the identity store service. It is returned in the API response if the total results are more than
        # the size of one page. This token is also returned when it is used in the API request to search for
        # the next page.

        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @groups : Array(Types::Group),
          @next_token : String? = nil
        )
        end
      end


      struct ListUsersRequest
        include JSON::Serializable

        # The globally unique identifier for the identity store, such as d-1234567890 . In this example, d- is
        # a fixed prefix, and 1234567890 is a randomly generated string that contains numbers and lower case
        # letters. This value is generated at the time that a new identity store is created.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # A collection of extension names indicating what extensions the service should retrieve alongside
        # other user attributes. aws:identitystore:enterprise is the only supported extension name.

        @[JSON::Field(key: "Extensions")]
        getter extensions : Array(String)?

        # A list of Filter objects, which is used in the ListUsers and ListGroups requests.

        @[JSON::Field(key: "Filters")]
        getter filters : Array(Types::Filter)?

        # The maximum number of results to be returned per request. This parameter is used in the ListUsers
        # and ListGroups requests to specify how many results to return in one page. The length limit is 50
        # characters.

        @[JSON::Field(key: "MaxResults")]
        getter max_results : Int32?

        # The pagination token used for the ListUsers and ListGroups API operations. This value is generated
        # by the identity store service. It is returned in the API response if the total results are more than
        # the size of one page. This token is also returned when it is used in the API request to search for
        # the next page.

        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @identity_store_id : String,
          @extensions : Array(String)? = nil,
          @filters : Array(Types::Filter)? = nil,
          @max_results : Int32? = nil,
          @next_token : String? = nil
        )
        end
      end


      struct ListUsersResponse
        include JSON::Serializable

        # A list of User objects in the identity store.

        @[JSON::Field(key: "Users")]
        getter users : Array(Types::User)

        # The pagination token used for the ListUsers and ListGroups API operations. This value is generated
        # by the identity store service. It is returned in the API response if the total results are more than
        # the size of one page. This token is also returned when it is used in the API request to search for
        # the next page.

        @[JSON::Field(key: "NextToken")]
        getter next_token : String?

        def initialize(
          @users : Array(Types::User),
          @next_token : String? = nil
        )
        end
      end

      # An object containing the identifier of a group member.

      struct MemberId
        include JSON::Serializable

        # An object containing the identifiers of resources that can be members.

        @[JSON::Field(key: "UserId")]
        getter user_id : String?

        def initialize(
          @user_id : String? = nil
        )
        end
      end

      # The full name of the user.

      struct Name
        include JSON::Serializable

        # The family name of the user.

        @[JSON::Field(key: "FamilyName")]
        getter family_name : String?

        # A string containing a formatted version of the name for display.

        @[JSON::Field(key: "Formatted")]
        getter formatted : String?

        # The given name of the user.

        @[JSON::Field(key: "GivenName")]
        getter given_name : String?

        # The honorific prefix of the user. For example, "Dr."

        @[JSON::Field(key: "HonorificPrefix")]
        getter honorific_prefix : String?

        # The honorific suffix of the user. For example, "M.D."

        @[JSON::Field(key: "HonorificSuffix")]
        getter honorific_suffix : String?

        # The middle name of the user.

        @[JSON::Field(key: "MiddleName")]
        getter middle_name : String?

        def initialize(
          @family_name : String? = nil,
          @formatted : String? = nil,
          @given_name : String? = nil,
          @honorific_prefix : String? = nil,
          @honorific_suffix : String? = nil,
          @middle_name : String? = nil
        )
        end
      end

      # The phone number associated with the user.

      struct PhoneNumber
        include JSON::Serializable

        # A Boolean value representing whether this is the primary phone number for the associated resource.

        @[JSON::Field(key: "Primary")]
        getter primary : Bool?

        # A string representing the type of a phone number. For example, "Mobile."

        @[JSON::Field(key: "Type")]
        getter type : String?

        # A string containing a phone number. For example, "8675309" or "+1 (800) 123-4567".

        @[JSON::Field(key: "Value")]
        getter value : String?

        def initialize(
          @primary : Bool? = nil,
          @type : String? = nil,
          @value : String? = nil
        )
        end
      end

      # Contains information about a user's photo. Users can have up to 3 photos, with one designated as
      # primary. Supports common image formats, including jpg, jpeg, png, and gif.

      struct Photo
        include JSON::Serializable

        # The photo data or URL. Supported formats include jpg, jpeg, png, and gif. This field is required for
        # all photo entries.

        @[JSON::Field(key: "Value")]
        getter value : String

        # A human-readable description of the photo for display purposes. This optional field provides context
        # about the photo.

        @[JSON::Field(key: "Display")]
        getter display : String?

        # Specifies whether this is the user's primary photo. Default value is false . Only one photo can be
        # designated as primary per user.

        @[JSON::Field(key: "Primary")]
        getter primary : Bool?

        # The type of photo. This field is optional and can be used to categorize different types of photos.

        @[JSON::Field(key: "Type")]
        getter type : String?

        def initialize(
          @value : String,
          @display : String? = nil,
          @primary : Bool? = nil,
          @type : String? = nil
        )
        end
      end

      # Indicates that a requested resource is not found.

      struct ResourceNotFoundException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        # Indicates the reason for a resource not found error when the service is unable to access a Customer
        # Managed KMS key. For non-KMS permission errors, this field is not included.

        @[JSON::Field(key: "Reason")]
        getter reason : String?

        # The identifier for each request. This value is a globally unique ID that is generated by the
        # identity store service for each sent request, and is then returned inside the exception if the
        # request fails.

        @[JSON::Field(key: "RequestId")]
        getter request_id : String?

        # The identifier for a resource in the identity store that can be used as UserId or GroupId . The
        # format for ResourceId is either UUID or 1234567890-UUID , where UUID is a randomly generated value
        # for each resource when it is created and 1234567890 represents the IdentityStoreId string value. In
        # the case that the identity store is migrated from a legacy SSO identity store, the ResourceId for
        # that identity store will be in the format of UUID . Otherwise, it will be in the 1234567890-UUID
        # format.

        @[JSON::Field(key: "ResourceId")]
        getter resource_id : String?

        # An enum object indicating the type of resource in the identity store service. Valid values include
        # USER, GROUP, and IDENTITY_STORE.

        @[JSON::Field(key: "ResourceType")]
        getter resource_type : String?

        def initialize(
          @message : String? = nil,
          @reason : String? = nil,
          @request_id : String? = nil,
          @resource_id : String? = nil,
          @resource_type : String? = nil
        )
        end
      end

      # The role associated with the user.

      struct Role
        include JSON::Serializable

        # A Boolean value representing whether this is the primary role for the associated resource.

        @[JSON::Field(key: "Primary")]
        getter primary : Bool?

        # A string representing the type of role. For example, "Work."

        @[JSON::Field(key: "Type")]
        getter type : String?

        # A string containing a role name. For example, "Researcher."

        @[JSON::Field(key: "Value")]
        getter value : String?

        def initialize(
          @primary : Bool? = nil,
          @type : String? = nil,
          @value : String? = nil
        )
        end
      end

      # The request would cause the number of users or groups in the identity store to exceed the maximum
      # allowed.

      struct ServiceQuotaExceededException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        # The identifier for each request. This value is a globally unique ID that is generated by the
        # identity store service for each sent request, and is then returned inside the exception if the
        # request fails.

        @[JSON::Field(key: "RequestId")]
        getter request_id : String?

        def initialize(
          @message : String? = nil,
          @request_id : String? = nil
        )
        end
      end

      # Indicates that the principal has crossed the throttling limits of the API operations.

      struct ThrottlingException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        # Indicates the reason for the throttling error when the service is unable to access a Customer
        # Managed KMS key. For non-KMS permission errors, this field is not included.

        @[JSON::Field(key: "Reason")]
        getter reason : String?

        # The identifier for each request. This value is a globally unique ID that is generated by the
        # identity store service for each sent request, and is then returned inside the exception if the
        # request fails.

        @[JSON::Field(key: "RequestId")]
        getter request_id : String?

        # The number of seconds to wait before retrying the next request.

        @[JSON::Field(key: "RetryAfterSeconds")]
        getter retry_after_seconds : Int32?

        def initialize(
          @message : String? = nil,
          @reason : String? = nil,
          @request_id : String? = nil,
          @retry_after_seconds : Int32? = nil
        )
        end
      end

      # An entity attribute that's unique to a specific entity.

      struct UniqueAttribute
        include JSON::Serializable

        # A string representation of the path to a given attribute or sub-attribute. Supports JMESPath.

        @[JSON::Field(key: "AttributePath")]
        getter attribute_path : String

        # The value of the attribute. This is a Document type. This type is not supported by Java V1, Go V1,
        # and older versions of the CLI.

        @[JSON::Field(key: "AttributeValue")]
        getter attribute_value : Types::AttributeValue

        def initialize(
          @attribute_path : String,
          @attribute_value : Types::AttributeValue
        )
        end
      end


      struct UpdateGroupRequest
        include JSON::Serializable

        # The identifier for a group in the identity store.

        @[JSON::Field(key: "GroupId")]
        getter group_id : String

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # A list of AttributeOperation objects to apply to the requested group. These operations might add,
        # replace, or remove an attribute. For more information on the attributes that can be added, replaced,
        # or removed, see Group .

        @[JSON::Field(key: "Operations")]
        getter operations : Array(Types::AttributeOperation)

        def initialize(
          @group_id : String,
          @identity_store_id : String,
          @operations : Array(Types::AttributeOperation)
        )
        end
      end


      struct UpdateGroupResponse
        include JSON::Serializable

        def initialize
        end
      end


      struct UpdateUserRequest
        include JSON::Serializable

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # A list of AttributeOperation objects to apply to the requested user. These operations might add,
        # replace, or remove an attribute. For more information on the attributes that can be added, replaced,
        # or removed, see User .

        @[JSON::Field(key: "Operations")]
        getter operations : Array(Types::AttributeOperation)

        # The identifier for a user in the identity store.

        @[JSON::Field(key: "UserId")]
        getter user_id : String

        def initialize(
          @identity_store_id : String,
          @operations : Array(Types::AttributeOperation),
          @user_id : String
        )
        end
      end


      struct UpdateUserResponse
        include JSON::Serializable

        def initialize
        end
      end

      # A user object that contains the metadata and attributes for a specified user.

      struct User
        include JSON::Serializable

        # The globally unique identifier for the identity store.

        @[JSON::Field(key: "IdentityStoreId")]
        getter identity_store_id : String

        # The identifier for a user in the identity store.

        @[JSON::Field(key: "UserId")]
        getter user_id : String

        # A list of Address objects containing addresses associated with the user.

        @[JSON::Field(key: "Addresses")]
        getter addresses : Array(Types::Address)?

        # The user's birthdate in YYYY-MM-DD format. This field stores personal birthdate information for the
        # user.

        @[JSON::Field(key: "Birthdate")]
        getter birthdate : String?

        # The date and time the user was created.

        @[JSON::Field(key: "CreatedAt", converter: Aws::Runtime::UnixTimestampConverter)]
        getter created_at : Time?

        # The identifier of the user or system that created the user.

        @[JSON::Field(key: "CreatedBy")]
        getter created_by : String?

        # A string containing the name of the user that is formatted for display when the user is referenced.
        # For example, "John Doe." Prefix search supports a maximum of 1,000 characters for the string.

        @[JSON::Field(key: "DisplayName")]
        getter display_name : String?

        # A list of Email objects containing email addresses associated with the user.

        @[JSON::Field(key: "Emails")]
        getter emails : Array(Types::Email)?

        # A map of explicitly requested attribute extensions associated with the user. Not populated if the
        # user has no requested extensions.

        @[JSON::Field(key: "Extensions")]
        getter extensions : Hash(String, Types::AttributeValue)?

        # A list of ExternalId objects that contains the identifiers issued to this resource by an external
        # identity provider.

        @[JSON::Field(key: "ExternalIds")]
        getter external_ids : Array(Types::ExternalId)?

        # A string containing the geographical region or location of the user.

        @[JSON::Field(key: "Locale")]
        getter locale : String?

        # An object containing the name of the user.

        @[JSON::Field(key: "Name")]
        getter name : Types::Name?

        # A string containing an alternate name for the user.

        @[JSON::Field(key: "NickName")]
        getter nick_name : String?

        # A list of PhoneNumber objects containing phone numbers associated with the user.

        @[JSON::Field(key: "PhoneNumbers")]
        getter phone_numbers : Array(Types::PhoneNumber)?

        # A list of photos associated with the user. Users can have up to 3 photos with metadata including
        # type, display name, and primary designation.

        @[JSON::Field(key: "Photos")]
        getter photos : Array(Types::Photo)?

        # A string containing the preferred language of the user. For example, "American English" or "en-us."

        @[JSON::Field(key: "PreferredLanguage")]
        getter preferred_language : String?

        # A string containing a URL that might be associated with the user.

        @[JSON::Field(key: "ProfileUrl")]
        getter profile_url : String?

        # A list of Role objects containing roles associated with the user.

        @[JSON::Field(key: "Roles")]
        getter roles : Array(Types::Role)?

        # A string containing the time zone of the user.

        @[JSON::Field(key: "Timezone")]
        getter timezone : String?

        # A string containing the title of the user. Possible values are left unspecified. The value can vary
        # based on your specific use case.

        @[JSON::Field(key: "Title")]
        getter title : String?

        # The date and time the user was last updated.

        @[JSON::Field(key: "UpdatedAt", converter: Aws::Runtime::UnixTimestampConverter)]
        getter updated_at : Time?

        # The identifier of the user or system that last updated the user.

        @[JSON::Field(key: "UpdatedBy")]
        getter updated_by : String?

        # A unique string used to identify the user. The length limit is 128 characters. This value can
        # consist of letters, accented characters, symbols, numbers, and punctuation. This value is specified
        # at the time the user is created and stored as an attribute of the user object in the identity store.

        @[JSON::Field(key: "UserName")]
        getter user_name : String?

        # The current status of the user account.

        @[JSON::Field(key: "UserStatus")]
        getter user_status : String?

        # A string indicating the type of user. Possible values are left unspecified. The value can vary based
        # on your specific use case.

        @[JSON::Field(key: "UserType")]
        getter user_type : String?

        # The user's personal website or blog URL. This field stores website information for personal or
        # professional use.

        @[JSON::Field(key: "Website")]
        getter website : String?

        def initialize(
          @identity_store_id : String,
          @user_id : String,
          @addresses : Array(Types::Address)? = nil,
          @birthdate : String? = nil,
          @created_at : Time? = nil,
          @created_by : String? = nil,
          @display_name : String? = nil,
          @emails : Array(Types::Email)? = nil,
          @extensions : Hash(String, Types::AttributeValue)? = nil,
          @external_ids : Array(Types::ExternalId)? = nil,
          @locale : String? = nil,
          @name : Types::Name? = nil,
          @nick_name : String? = nil,
          @phone_numbers : Array(Types::PhoneNumber)? = nil,
          @photos : Array(Types::Photo)? = nil,
          @preferred_language : String? = nil,
          @profile_url : String? = nil,
          @roles : Array(Types::Role)? = nil,
          @timezone : String? = nil,
          @title : String? = nil,
          @updated_at : Time? = nil,
          @updated_by : String? = nil,
          @user_name : String? = nil,
          @user_status : String? = nil,
          @user_type : String? = nil,
          @website : String? = nil
        )
        end
      end

      # The request failed because it contains a syntax error.

      struct ValidationException
        include JSON::Serializable


        @[JSON::Field(key: "Message")]
        getter message : String?

        # Indicates the reason for the validation error when the service is unable to access a Customer
        # Managed KMS key. For non-KMS permission errors, this field is not included.

        @[JSON::Field(key: "Reason")]
        getter reason : String?

        # The identifier for each request. This value is a globally unique ID that is generated by the
        # identity store service for each sent request, and is then returned inside the exception if the
        # request fails.

        @[JSON::Field(key: "RequestId")]
        getter request_id : String?

        def initialize(
          @message : String? = nil,
          @reason : String? = nil,
          @request_id : String? = nil
        )
        end
      end
    end
  end
end
